scripts/initial_setup.bat
scripts/initial_setup.sh
src/agent_c_reference_apps/pyproject.toml
src/agent_c_reference_apps/src/agent_c_reference_apps/agent_c_gradio.py
src/agent_c_reference_apps/src/agent_c_reference_apps/ui/gradio_ui.py
src/agent_c_tools/pyproject.toml

This pull request includes several changes to the setup scripts and the `agent_c_reference_apps` project to improve virtual environment handling and remove unused dependencies.
* [`scripts/initial_setup.bat`](diffhunk://#diff-9f0788522d27598f85ee067fbc160a216a9356615e2117c4f2672f8256de9735L12-R17): Changed virtual environment directory from `venv` to `.venv` and updated related commands. [[1]](diffhunk://#diff-9f0788522d27598f85ee067fbc160a216a9356615e2117c4f2672f8256de9735L12-R17) [[2]](diffhunk://#diff-9f0788522d27598f85ee067fbc160a216a9356615e2117c4f2672f8256de9735L26-R26) [[3]](diffhunk://#diff-9f0788522d27598f85ee067fbc160a216a9356615e2117c4f2672f8256de9735L43-R43)
* [`scripts/initial_setup.sh`](diffhunk://#diff-4c93955ef4d8c9650aef19be7fd7da249d9160dffbb287ef04c4f906c57d1948L11-R27): …

Fix a bunch of issues on clean machines since the export

---

personas/toolman.md
scripts/install_deps.bat
scripts/install_deps.sh
src/agent_c_reference_apps/src/agent_c_reference_apps/agent_c_gradio.py
src/my_agent_c/pyproject.toml
src/my_agent_c/src/my_agent_c/tools/__init__.py

This pull request introduces a new project structure for `my_agent_c` and updates various files to reflect this addition. The most important changes include updating the general guidelines, installation scripts, and dependencies to incorporate `my_agent_c`.
* [`personas/toolman.md`](diffhunk://#diff-e6955afc5ca665d0be3aea31d28aec810be9dca3ae008f51d0904afafd76fadfL35-L43): Added `my_agent_c` to the project structure and updated the source conventions to reflect the new folder structure. [[1]](diffhunk://#diff-e6955afc5ca665d0be3aea31d28aec810be9dca3ae008f51d0904afafd76fadfL35-L43) [[2]](diffhunk://#diff-e6955afc5ca665d0be3aea31d28aec810be9dca3ae008f51d0904afafd76fadfR53-R59) [[3]](diffhunk://#diff-e6955afc5ca665d0be3aea31d28aec810be9dca3ae008f51d0904afafd76fadfL72-R77)
* …

Fix Toolman to use my_agent_c as a target not agent_c_demo.

---

src/agent_c_core/src/agent_c/agents/gpt.py

This pull request includes a small change to the `src/agent_c_core/src/agent_c/agents/gpt.py` file. The change adds support for the models `gpt-o3` and `gpt-o3-mini` to set the `root_message_role` to "developer".

add o3 to the list of models that use developer messages.

---

src/agent_c_core/src/agent_c/agents/gpt.py

This pull request includes a change to the `__init__` method in the `src/agent_c_core/src/agent_c/agents/gpt.py` file. The change updates the model names in the conditional check for setting the `root_message_role` attribute.
* [`src/agent_c_core/src/agent_c/agents/gpt.py`](diffhunk://#diff-0b0b2a2155f664049de21c3c667705f1c11a5613fc2949087029caaff07e36cfL65-R65): Updated model names in the conditional check from "gpt-o1", "gpt-o1-mini", "gpt-o3", and "gpt-o3-mini" to "o1", "o1-mini", "o3", and "o3-mini".

Fix model names

---

src/agent_c_core/src/agent_c/agents/gpt.py

`reasoning_effort` should be a string in the for of  low, medium, high.  The default is medium.
This pull request includes updates to the `__interaction_setup` method in the `src/agent_c_core/src/agent_c/agents/gpt.py` file. The changes focus on refining the completion options based on specific conditions and adding a new parameter to the completion options.
Key changes include:
* Conditional model handling: Added specific model names to handle completion options differently when the model is one of ["o1", 'o1-mini', 'o3', 'o3-mini'] (`[src/agent_c_core/src/agent_c/agents/gpt.pyR124-R128](diffhunk://#diff-0b0b2a2155f664049de21c3c667705f1c11a5613fc2949087029caaff07e36cfR124-R128)`).
* New parameter addition: Included a new `reasoning_effort` parameter in the completion options if it is …

Allow reasoning effort in completion options

---

personas/toolman.md
src/agent_c_core/src/agent_c/agents/base.py
src/agent_c_core/src/agent_c/agents/claude.py
src/agent_c_core/src/agent_c/agents/gpt.py
src/agent_c_core/src/agent_c/models/events/__init__.py
src/agent_c_core/src/agent_c/models/events/base.py
src/agent_c_core/src/agent_c/models/events/chat.py
src/agent_c_core/src/agent_c/models/events/render_media.py
src/agent_c_core/src/agent_c/models/events/session_event.py
src/agent_c_core/src/agent_c/models/events/tool_calls.py
src/agent_c_core/src/agent_c/toolsets/tool_set.py
src/agent_c_reference_apps/src/agent_c_reference_apps/agent_c_cli.py
src/agent_c_reference_apps/src/agent_c_reference_apps/ui/console_chat_ui.py
src/agent_c_reference_apps/src/agent_c_reference_apps/ui/gradio_ui.py
src/agent_c_tools/src/agent_c_tools/tools/dall_e/tool.py
src/agent_c_tools/src/agent_c_tools/tools/mermaid_chart/tool.py
src/agent_c_tools/src/agent_c_tools/tools/web/tool.py

Big refactor of the event stream:
- ChatEvent has been broken into multiple events
- A new tool choice delta event that contains the tool_call list as it's being constructed by the model exists now.
- Token usage metrics are now reported at the end of each completion.
- Both GPT and Cluade completions emit consistent event flows.
- ALSO refactored the GPT Agent chat method to look more like the Claude one.
- `tool_choice` for GPT is now supported in the chat call.
This pull request includes several significant changes aimed at refactoring and enhancing the functionality of the `agent_c` module. The changes include updates to event handling, introduction of new methods for raising events, and modifications to the interaction setup process. Here are the most important changes:
* **Event …

Refactor the ChatEvent into smaller focused events + a bonus

---

dockerfiles/Dockerfile.dev
dockerfiles/README.md
example.env
src/agent_c_reference_apps/src/agent_c_reference_apps/ui/gradio_ui.py

This pull request includes several updates to the development Dockerfile, environment configuration, and Gradio UI settings. The most important changes include updating the base image and dependencies in the Dockerfile, modifying environment variables in the example environment file, and adjusting the Gradio UI launch settings.
* Updated the base image to `python:3.12-slim-bullseye` and added new dependencies such as `chromium`, `chromium-driver`, and `cmake`. [[1]](diffhunk://#diff-3aa78c91b034247916310da7f568d894c859d54e0ba88442e062c3f11a8e62b9L1-R7) [[2]](diffhunk://#diff-3aa78c91b034247916310da7f568d894c859d54e0ba88442e062c3f11a8e62b9L17-R24)
* Added the installation of the `zep_cloud` Python package.
* Changed the entry point command to run the Gradio UI instead of the CLI.
* Removed …

Get the deference apps running in rocker

---

dockerfiles/api.Dockerfile
dockerfiles/docker-compose.yml

This pull request includes changes to the Docker configuration files to ensure the personas directory is included and mounted properly. The most important changes are:
Dockerfile updates:
* [`dockerfiles/api.Dockerfile`](diffhunk://#diff-158a1dffd1eea9c866e9b45df11703f291fd1d05f7f35f12c527d3e1b05244afR27-R29): Added a step to copy the `personas` directory into the Docker image.
Docker Compose updates:
* [`dockerfiles/docker-compose.yml`](diffhunk://#diff-68e819f6c4b1c7db3b92c765cd799e8c5344688e73b6caa47fad6beadc3ef4bdR13): Added a volume mount for the `personas` directory to the `services` section to support persona selection.

Adding personas to docker containers

---

dockerfiles/docker-compose.yml
dockerfiles/frontend.Dockerfile

This pull request includes updates to the Docker configuration for the frontend service. The most significant changes involve commenting out the volume mounting for development hot-reloading, installing additional dependencies, and adding a workaround for a rollup dependency issue.
Updates to Docker configuration:
* [`dockerfiles/docker-compose.yml`](diffhunk://#diff-68e819f6c4b1c7db3b92c765cd799e8c5344688e73b6caa47fad6beadc3ef4bdL30-R31): Commented out the volume mounting for development hot-reloading.
* [`dockerfiles/frontend.Dockerfile`](diffhunk://#diff-78478502c1c5dbd2db98c021fc4129482653bb3bba089408f794c6a42d420d36R9-R26): Added `build-essential` and `python3` to the list of dependencies to be installed.
* [`dockerfiles/frontend.Dockerfile`](diffhunk://#diff-78478502c1c5dbd2db98c021f …

Fix a compose issue with the frontend

---

personas/carl.md
personas/joe.md
personas/matz.md
personas/py_polish.md
personas/pyper.md
personas/toolman.md

This pull request includes updates to various persona files to ensure best practices and current language versions are assumed. The changes are mainly focused on adding guidelines for using the latest versions of languages and packages, and avoiding deprecated syntax.
Updates to persona guidelines:
* [`personas/carl.md`](diffhunk://#diff-1d8feef622cdc4363c651227e84c60888df96bd73374a60e39f609b2b6c39095R10-R11): Added guidelines to assume the latest version of the language and packages, and to avoid deprecated syntax.
* [`personas/joe.md`](diffhunk://#diff-a300ea99d38ea2d7b6a31677bf431c65082ddcd4f7f67641110f4a1897dbf1b1R10-R11): Added guidelines to assume the latest version of the language and packages, and to avoid deprecated syntax.
* …

Add rule for language versions

---

.github/workflows/build-and-publish-python-packages.yml
.github/workflows/main-docker-build-and-push.yml
.github/workflows/tagged-docker-build-and-push.yml
ci/bump_version.py

This pull request introduces a GitHub Actions workflow to automate the build and publish process for Python packages and includes a script to bump the version of the packages. The most important changes include the addition of the workflow configuration and the version bumping script.
Workflow automation:
* [`.github/workflows/build-and-publish-python-packages.yml`](diffhunk://#diff-1ba28fd6c8983f7f2a87b2828b0710209a102cbfea2a8b780ac229faf65e567bR1-R124): Added a new GitHub Actions workflow to build and publish Python packages for `agent_c_core`, `agent_c_tools`, and `agent_c_reference_apps`. The workflow triggers on pushes to the main branch and checks for changes in specific directories before proceeding with the build and publish steps.
Version bumping script:
* …

add workflow to publish python packages

---

.github/workflows/build-and-publish-python-packages.yml

This pull request includes updates to the GitHub Actions workflow for building and publishing Python packages. The most important change is the addition of steps to set up Python and upgrade pip and install necessary build tools.
Workflow updates:
* [`.github/workflows/build-and-publish-python-packages.yml`](diffhunk://#diff-1ba28fd6c8983f7f2a87b2828b0710209a102cbfea2a8b780ac229faf65e567bR56-R65): Added a step to set up Python using `actions/setup-python@v4` with Python version 3.12.
* [`.github/workflows/build-and-publish-python-packages.yml`](diffhunk://#diff-1ba28fd6c8983f7f2a87b2828b0710209a102cbfea2a8b780ac229faf65e567bR56-R65): Added a step to upgrade pip and install build tools including `build`, `twine`, and `toml`.

fix python runner?

---

.github/workflows/build-and-publish-python-packages.yml

This pull request includes updates to the GitHub Actions workflow for building and publishing Python packages. The changes focus on setting up the Python environment and upgrading pip and build tools.
Key changes:
* [`.github/workflows/build-and-publish-python-packages.yml`](diffhunk://#diff-1ba28fd6c8983f7f2a87b2828b0710209a102cbfea2a8b780ac229faf65e567bR18-R27): Added steps to set up Python 3.12 and upgrade pip and install build tools in two different job sections. [[1]](diffhunk://#diff-1ba28fd6c8983f7f2a87b2828b0710209a102cbfea2a8b780ac229faf65e567bR18-R27) [[2]](diffhunk://#diff-1ba28fd6c8983f7f2a87b2828b0710209a102cbfea2a8b780ac229faf65e567bR113-R122)

Make sure each package gets toml installed and the right python version

---

.github/workflows/build-and-publish-python-packages.yml

This pull request includes a small change to the `.github/workflows/build-and-publish-python-packages.yml` file. The change updates the list of build tools to include `setuptools` during the pip installation process.
* [`.github/workflows/build-and-publish-python-packages.yml`](diffhunk://#diff-1ba28fd6c8983f7f2a87b2828b0710209a102cbfea2a8b780ac229faf65e567bL121-R121): Added `setuptools` to the list of packages installed by pip.

Add setuprools to the package runner

---

.github/workflows/build-and-publish-python-packages.yml

This pull request includes changes to the `.github/workflows/build-and-publish-python-packages.yml` file to ensure that the correct directories are targeted when publishing packages to GitHub Packages.
Improvements to the publishing process:
* [`.github/workflows/build-and-publish-python-packages.yml`](diffhunk://#diff-1ba28fd6c8983f7f2a87b2828b0710209a102cbfea2a8b780ac229faf65e567bR52): Added `cd` commands to navigate to the appropriate directories before running the `twine upload` command for the `agent_c_core`, `agent_c_tools`, and `agent_c_reference_apps` packages. [[1]](diffhunk://#diff-1ba28fd6c8983f7f2a87b2828b0710209a102cbfea2a8b780ac229faf65e567bR52) [[2]](diffhunk://#diff-1ba28fd6c8983f7f2a87b2828b0710209a102cbfea2a8b780ac229faf65e567bR100) …

Make sure the package runner CDs into the right folder

---

.github/workflows/build-and-publish-python-packages.yml

This pull request includes changes to the build and publish workflow for Python packages in the `.github/workflows/build-and-publish-python-packages.yml` file. The changes focus on removing redundant dependencies, setting up the GitHub Packages environment, and modifying the publishing process.
Improvements to dependency management:
* Removed `toml` from the list of dependencies installed during the upgrade step. [[1]](diffhunk://#diff-1ba28fd6c8983f7f2a87b2828b0710209a102cbfea2a8b780ac229faf65e567bL29-R29) [[2]](diffhunk://#diff-1ba28fd6c8983f7f2a87b2828b0710209a102cbfea2a8b780ac229faf65e567bL80-R92) [[3]](diffhunk://#diff-1ba28fd6c8983f7f2a87b2828b0710209a102cbfea2a8b780ac229faf65e567bL130-R154)
Setup of GitHub Packages environment:
* Added a step to set up the GitHub Packages …

package workflow shot in the dark #399

---

dockerfiles/base/python/Dockerfile

This pull request includes a small change to the `dockerfiles/base/python/Dockerfile` file. The change removes the installation of `vim` from the list of packages to be installed.
* [`dockerfiles/base/python/Dockerfile`](diffhunk://#diff-e9711fa761dcb0a039847fa35d5b29468378cf5037f8206b87536429775264bfL17): Removed `vim` from the list of packages to be installed.

Test the new pipeline

---

.github/workflows/main-docker-build-and-push.yml
dockerfiles/base/python/Dockerfile

This pull request includes several improvements to the Docker build and push workflow, as well as minor adjustments to the Dockerfile for better organization and clarity.
Improvements to Docker build and push workflow:
* [`.github/workflows/main-docker-build-and-push.yml`](diffhunk://#diff-3db748f55b3db39372c7ab5180021da288e8e4e875fa3644787e4e54024e0784R53-R78): Added steps to verify registry login and ensure the base image is successfully pushed. This includes logging into `ghcr.io` and checking the event name, as well as verifying that the base image was published and can be pulled.
Adjustments to Dockerfile:
* [`dockerfiles/base/python/Dockerfile`](diffhunk://#diff-e9711fa761dcb0a039847fa35d5b29468378cf5037f8206b87536429775264bfL35-L38): Removed redundant comments and commands related …

I hate workflows

---

src/agent_c_tools/src/agent_c_tools/tools/rss/feeds.py

This pull request includes updates to the `feeds.py` file in the `agent_c_tools` module to add new RSS feeds for consulting firms Markovate and RTS Labs. The changes involve adding new constants for the URLs of these feeds and including them in the `default_feeds` list.
New RSS feeds added:
* Added `MARKOVATE_BLOG` and `MARKOVATE_STORIES` constants for Markovate Consulting feeds.
* Added `RTS_LABS_BLOG` constant for RTS Labs Consulting feed.
Updates to `default_feeds` list:
* Included Markovate Consulting blog and web stories feeds in the `default_feeds` list.
* Included RTS Labs blog feed in the `default_feeds` list.

add a couple RSS feeds

---

.github/workflows/main-docker-build-and-push.yml

This pull request updates the GitHub Actions workflow for building and pushing Docker images. The main changes involve modifying the conditions under which Docker images are pushed to the repository. These changes ensure that images are pushed on pull request close, push to the main branch, or manual dispatch.
Key changes include:
* Updated the `pull_request` and `push` triggers to include branches and event types for building and pushing Docker images. (`.github/workflows/main-docker-build-and-push.yml`)
* Modified the `push` condition in the `jobs:` section to push images on PR close, push to main, or manual dispatch for the base Python image. (`.github/workflows/main-docker-build-and-push.yml`)
* Updated the `push` condition for the API Dockerfile to push images on PR close, push to …

Fix the workflow to acutally publish the containers

---

src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_manager.py
src/agent_c_api_ui/agent_c_api/src/agent_c_api/tests/persona_test.py

This pull request focuses on renaming the `custom_persona_text` attribute to `custom_prompt` across various parts of the codebase to improve clarity and consistency. The changes span multiple files, including the main agent manager and associated tests.
* [`src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_manager.py`](diffhunk://#diff-2c4bb947c744aebea2a57649aee31da1fa01b19205514e829b50a624d228c2e7L78-R79): Updated the `create_session` method to use `custom_prompt` instead of `custom_persona_text`. This includes the extraction of the custom prompt from `kwargs`, preserving the existing custom prompt during model changes, and initializing the agent with the new `custom_prompt` attribute. [[1]](diffhunk://#diff-2c4bb947c744aebea2a57649aee31da1fa01b19205514e829b50a624d228c2e7L78-R79) …

Found edge case that needed fixed.

---

README.md

It said OPEN_API_KEY instead of OPENAI_API_KEY. fixed

Fixed key name

---

ci/build_api_container.bat
ci/build_fe_container.bat
src/agent_c_core/pyproject.toml
src/agent_c_core/src/agent_c/agents/claude.py

The Claude Chat agent will now enable two Anthropic betas when your model is 3.7-sonnet
-[ Token-efficient tool use](https://docs.anthropic.com/en/docs/build-with-claude/tool-use/token-efficient-tool-use) - This is supposed to help with the regression in 3.7 around parallel tool calls.  Note: It does NOT make it STFU while calling tools.
- output-128k-2025-02-19  - This one slipped through the cracks for me when I added the 3.7 support.  I didn't catch that 128k required a beta header.
--- 
This pull request includes several changes to the build process, dependency updates, and enhancements to the `claude` agent functionality. The most important changes are summarized below:
* [`ci/build_api_container.bat`](diffhunk://#diff-39a5d1f8c630792a4b8165e6fcdfd3f7f7b9cc38d256e0f3e001190b77d75af6R1 …

Add support for the Anthropic betas

---

personas/toolman.md
src/agent_c_core/src/agent_c/util/string.py
src/agent_c_tools/src/agent_c_tools/tools/workspaces/base.py
src/agent_c_tools/src/agent_c_tools/tools/workspaces/local_storage.py
src/agent_c_tools/src/agent_c_tools/tools/workspaces/tool.py

This pull request introduces several enhancements to the `Agent C` project, focusing on improving the directory structure visualization and refining the workspace tools. The key changes include the addition of a new method to generate and display a directory tree, updates to handle ignored patterns, and adjustments to the workspace tool methods to support these new functionalities.
Enhancements to directory structure visualization:
* [`src/agent_c_core/src/agent_c/util/string.py`](diffhunk://#diff-da82db502d3872531746a21ee228f506c4b415becad9a2d29fd12e18620b73e1R1-R6): Added `DEFAULT_TREE_IGNORE_PATTERNS` and updated `generate_path_tree` to accept an `ignore_patterns` parameter, filtering out specified patterns while generating the directory tree. …

Add trees to the workspace tool

---

src/agent_c_tools/src/agent_c_tools/tools/workspaces/tool.py

This pull request includes a change to the `src/agent_c_tools/src/agent_c_tools/tools/workspaces/tool.py` file to rename an asynchronous method for better clarity.
Method renaming:
* [`src/agent_c_tools/src/agent_c_tools/tools/workspaces/tool.py`](diffhunk://#diff-cefcf924f830234faf7938a40eec65afe66de2726e633965ccbe7ba78947fc59L97-R97): Renamed the `ls` method to `tree` to better reflect its functionality of listing the contents of a workspace or a subdirectory in it.

Fix the tree tool name

---

src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/util/logging_utils.py
src/agent_c_core/src/agent_c/agents/claude.py
src/agent_c_tools/README.md
src/agent_c_tools/src/agent_c_tools/tools/web/tool.py

This pull request includes several updates to the `agent_c` project, focusing on improving error handling, adding new features for web scraping tools, and updating logging configurations.
Error Handling Enhancements:
* Added `RateLimitError` and `OverloadedError` to the list of exceptions handled in the `chat` method of the `Claude` agent. The system now logs the specific error type and performs exponential backoff accordingly.
Web Scraping Tool Enhancements:
* Updated the `web` tool to include options for saving scraped web pages as markdown files to workspaces. New parameters `save_to_workspace`, `workspace_name`, and `file_path` were added to the `open_webpage` and `fetch_webpage` methods. [[1]](diffhunk://#diff-1906871bc5bdabcc8a7b7cceb977bbb980e010f44eb12bd09a3b236e22c2aa9eR102-R118) …

Added ratelimit, overload to backoff for Claude.

---

src/agent_c_core/src/agent_c/prompting/basic_sections/persona.py

This pull request makes a minor adjustment to the `rendered_persona_prompt` method in the `persona.py` file to reduce the depth of the workspace tree retrieval.
Key change:
* [`src/agent_c_core/src/agent_c/prompting/basic_sections/persona.py`](diffhunk://#diff-7395d7a06588f54c8751a6861042068a9de0af646b8db59909cfcc9c3edf1b80L99-R99): Updated the `tree` method call to reduce `folder_depth` from 7 to 5 and `file_depth` from 7 to 2, optimizing the workspace tree retrieval process for efficiency.

Change tree size for personas

---

src/agent_c_tools/src/agent_c_tools/tools/web/tool.py

This pull request introduces several updates to the `WebTools` class in `src/agent_c_tools/tools/web/tool.py`, focusing on improving functionality for web content handling, error logging, and adding a new method for saving fetched web content to a workspace. Key changes include the addition of a new `fetch_and_save` method, improved error logging, and minor formatting adjustments.
* **Added `fetch_and_save` method**: Introduced a new method to fetch web page content, save it to a workspace, and optionally return it in Markdown format. This includes handling workspace and file path validation, generating default file paths, and saving content using the workspace toolset.
* **Enhanced error logging**: Updated error messages in `fetch_webpage` to include more descriptive prefixes (e.g., "An …

Webtool tweak

---

src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_manager.py

This pull request makes a small change to the `ESSENTIAL_TOOLS` list in the `UItoAgentBridgeManager` class by removing the `MemoryTools` entry. This change reduces the set of essential tools used in the `agent_manager.py` file.

Removing MemoryTool from agent_manager.py

---

src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_bridge.py

This pull request introduces a minor enhancement to the `agent_bridge.py` file by incorporating a new section into the agent's initialization process, which could potentially improve its functionality.
Enhancements to agent initialization:
* [`src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_bridge.py`](diffhunk://#diff-28bc5184f60b617647c44cd86d7e90885fee567cc04bad4bdf9ffda2f4e533d7L26-R26): Added the `ThinkSection` import and included it in the `operating_sections` list within the `initialize_agent_parameters` method. This change likely enables the agent to utilize additional capabilities or logic provided by the `ThinkSection`. [[1]](diffhunk://#diff-28bc5184f60b617647c44cd86d7e90885fee567cc04bad4bdf9ffda2f4e533d7L26-R26) …

Missed a scection in the prompt refactor

---

personas/cora-agent_c_core_dev.md
src/agent_c_tools/src/agent_c_tools/tools/markdown_to_html_report/markdown-viewer-template.html

This pull request introduces improvements to the `Agent C Output Viewer` for better user experience and removes redundant guidance in the scratchpad documentation. The key changes include adding a helper function to format file and folder names in the tree view and cleaning up unnecessary scratchpad instructions.
* Added a `formatDisplayName` helper function to clean and format file and folder names. This includes removing leading numbers, file extensions, and underscores, and applying title case for better readability. (`src/agent_c_tools/src/agent_c_tools/tools/markdown_to_html_report/markdown-viewer-template.html`, [src/agent_c_tools/src/agent_c_tools/tools/markdown_to_html_report/markdown-viewer-template.htmlR655-R681](diffhunk://#diff-ff3e1ec512e4d8f104d4753eb83b8efe6c4561bab01e29b68d …

Make markdown report titles pretty

---

src/agent_c_tools/src/agent_c_tools/tools/workspace/local_storage.py

This pull request includes a small but important change to the `read_internal` method in `local_storage.py`. The change ensures that file reading operations handle encoding errors gracefully by replacing invalid characters.
* [`src/agent_c_tools/src/agent_c_tools/tools/workspace/local_storage.py`](diffhunk://#diff-4823fbec81d92cbc7dce6433774154eff330954f9fe968dbb02d3f1c4668164dL205-R205): Updated the `open` function in the `read_internal` method to include the `errors='replace'` parameter, which replaces invalid characters during file reading instead of raising an exception.

Adding UTF-8 read char error with replace.

---

src/agent_c_api_ui/agent_c_react_client/package.json

This pull request includes a small change to the `package.json` file for the `agent_c_react_client` project. The change adds the `@rollup/rollup-win32-x64-msvc` dependency with version `^4.40.0` to the list of dependencies.

Fix missing dependency with front end

---

src/agent_c_tools/src/agent_c_tools/tools/workspace/tool.py

This pull request updates the imports in the `src/agent_c_tools/src/agent_c_tools/tools/workspace/tool.py` file to include additional type hints. The change expands the range of type annotations available for use within the file.
Key change:
* Updated the `typing` imports to include `Callable`, `Awaitable`, and `Union`, enabling more precise type annotations for functions and asynchronous operations.

fix imports

---

src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_bridge.py
src/agent_c_core/src/agent_c/toolsets/tool_chest.py

This pull request focuses on improving file handling, debugging code, and method naming in the `agent_c_api` and `tool_chest` modules. The changes enhance code readability, maintainability, and functionality. Below is a summary of the most important changes grouped by theme:
* Replaced the direct `open` function with a context manager (`with open(...)`) for safer file handling in `__init_workspaces`. This ensures the file is properly closed after use. (`src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_bridge.py`, [src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_bridge.pyL224-R226](diffhunk://#diff-28bc5184f60b617647c44cd86d7e90885fee567cc04bad4bdf9ffda2f4e533d7L224-R226))
* Removed unnecessary intermediate dictionary (`tool_class_to_instance_name`) in the …

Fix some issues with the way agent bridge and toolchest interact

---

src/agent_c_core/src/agent_c/prompting/basic_sections/persona.py

This pull request includes a small change to the `rendered_persona_prompt` method in `persona.py`. The change updates the key used to retrieve the workspace tool from `tool_chest` to reflect a corrected or updated naming convention.
* [`src/agent_c_core/src/agent_c/prompting/basic_sections/persona.py`](diffhunk://#diff-7395d7a06588f54c8751a6861042068a9de0af646b8db59909cfcc9c3edf1b80L97-R97): Changed the key from `'workspace'` to `'WorkspaceTools'` when accessing `active_tools` in the `tool_chest` context.

Fix dyanmic person to fetch workspace properly now

---

src/agent_c_tools/src/agent_c_tools/tools/tool_debugger/README.md
src/agent_c_tools/src/agent_c_tools/tools/tool_debugger/debug_tool.py
src/agent_c_tools/src/agent_c_tools/tools/tool_debugger/example.py
src/agent_c_tools/src/agent_c_tools/tools/tool_debugger/example2.py
src/agent_c_tools/src/agent_c_tools/tools/tool_debugger/example3.py

This pull request introduces a new `ToolDebugger` utility for testing and debugging tools in the `agent_c_tools` package. The changes include the implementation of the `ToolDebugger` class, comprehensive documentation, and example scripts to demonstrate its usage. The most important changes are grouped into the following themes:
* Added the `ToolDebugger` class in `debug_tool.py`, which provides methods for dynamically importing, configuring, and testing tools, including handling dependencies and workspaces. Key methods include `setup_tool`, `run_tool_test`, `print_tool_info`, `extract_content_from_results`, and `extract_structured_content`.
* Introduced a mock `TokenCounter` class to resolve dependency issues when using tools without an agent.
* Created a detailed `README.md` file for …

Adding a tool debugger

---

src/agent_c_core/src/agent_c/agents/claude.py
src/agent_c_tools/src/agent_c_tools/tools/workspace_planning/tool.py

This pull request includes updates to asynchronous methods in the `agent_c` project to improve functionality and ensure consistency. The changes primarily involve modifying method calls to align with updated asynchronous patterns.
* [`src/agent_c_core/src/agent_c/agents/claude.py`](diffhunk://#diff-d74867587f97368abcc0acaafc2f218509185212937c61d43c07a7fc5b791876L598-R598): Updated the `__tool_calls_to_messages` method to use `state['collected_tool_calls']` instead of the `tool_calls` parameter, ensuring the correct data is passed to the `ToolChest.call_tools` method.
* [`src/agent_c_tools/src/agent_c_tools/tools/workspace_planning/tool.py`](diffhunk://#diff-31898117c06d69eb03a8b2fb3146b943581c64421fd3d595982762d14e781318L597-R597): Modified the `export_plan_report` method to call …

Fix tools calls, add an export to the planner

---

src/agent_c_core/src/agent_c/agents/claude.py

This pull request includes a change in the `__interaction_setup` method of the `claude.py` file to temporarily disable certain functionalities related to web search and code execution by commenting out their corresponding configurations.
Changes to functionality:
* In `src/agent_c_core/src/agent_c/agents/claude.py`, the `web_search` function and the `code_execution` function have been commented out, effectively disabling these features. Additionally, references to the `code-execution-2025-05-22` beta have been commented out in the `completion_opts['betas']` configuration. These changes likely aim to temporarily disable these features for testing or debugging purposes.

disable server side tools for now

---

src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_bridge.py

This pull request adds a new toolset to the list of essential tools in the `AgentBridge` class. 
* Updated the `essential_toolsets` list in `AgentBridge` to include `'MarkdownToHtmlReportTools'`, ensuring support for converting Markdown to HTML reports. (`src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_bridge.py`, [src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_bridge.pyL155-R155](diffhunk://#diff-28bc5184f60b617647c44cd86d7e90885fee567cc04bad4bdf9ffda2f4e533d7L155-R155))
* The omission was causing the tool to neither be initialized, nor available in the UI.

Add MarkdownToHtmlReportTools to essential toolsets

---

src/agent_c_tools/src/agent_c_tools/tools/agent_assist/base.py
src/agent_c_tools/src/agent_c_tools/tools/agent_assist/prompt.py

This pull request refactors variable naming for consistency and improves readability in the `agent_assist` module. The changes primarily involve renaming variables and updating references to align with the new naming conventions.
* [`src/agent_c_tools/src/agent_c_tools/tools/agent_assist/base.py`](diffhunk://#diff-0bba289e4bb4fa9c43eaa70e7440677a9854883688d01e559748cfd66cf8195aL143-R147): Renamed the `agent` parameter to `agent_config` in the `__build_prompt_metadata` method and updated all references accordingly. This ensures the variable name reflects its purpose more clearly.
* [`src/agent_c_tools/src/agent_c_tools/tools/agent_assist/prompt.py`](diffhunk://#diff-eb80e308688009ce4ab4020fca80a45666f80cf807b052ef78a542f90072ec41L56-R57): Updated the `agent` variable to `agent_config` in …

Ensure AA to AC tool handoff works

---

src/agent_c_tools/src/agent_c_tools/tools/web/tool.py
src/agent_c_tools/src/agent_c_tools/tools/workspace/base.py
src/agent_c_tools/src/agent_c_tools/tools/workspace/tool.py

This pull request includes updates to improve functionality and code clarity in the `agent_c_tools` package, specifically in metadata handling and content fetching. The most important changes include refining metadata key processing, improving YAML dumping for metadata keys, and clarifying the description of a configuration parameter.
* [`src/agent_c_tools/src/agent_c_tools/tools/workspace/base.py`](diffhunk://#diff-caa6471e2d1e0a64861682cba781a758c1a46454d5658a7fb609ff73d68b861dL246-R248): Added checks to ensure `key` is valid before processing it into parts, improving robustness in metadata key handling.
* [`src/agent_c_tools/src/agent_c_tools/tools/workspace/tool.py`](diffhunk://#diff-976a05154098ea3a00cfc53aced20fa20d459c68732d32a83c95a832e45b9fd2L899-R900): Replaced direct YAML …

Fix getting the root meta keys

---

src/agent_c_tools/pyproject.toml

This pull request adds a new dependency to the `src/agent_c_tools/pyproject.toml` file. The `huggingface_hub` library, version 0.33.0, is now included in the project's dependencies.

Add missing dep

---

dockerfiles/api.Dockerfile

This pull request makes a small change to the `dockerfiles/api.Dockerfile` by removing the line that copies the `personas` directory into the Docker image. This change simplifies the Dockerfile, likely because the `personas` directory is no longer required in the image or is being handled differently.

Fixed broken dockerfile build

---

src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/realtime_bridge.py

This pull request refactors the logic for sending the avatar list in the `realtime_bridge.py` file to improve clarity and ensure that the correct event is sent in all cases.
Error handling and event emission improvements:
* Refactored the `send_avatar_list` method to explicitly check for the presence of `heygen_client`, ensuring that `AvatarListEvent` is sent with either the fetched avatar data or an empty list if the client is not available.

Refactor send_avatar_list to handle missing heygen_client more clearly

---

src/agent_c_tools/src/agent_c_tools/tools/workspace/local_storage.py

This pull request updates the `grep` method in `local_storage.py` to improve search efficiency and relevance by excluding common directories that typically contain non-source or irrelevant files.
Improvements to search functionality:
* Added logic to exclude directories such as `.git`, `node_modules`, `__pycache__`, `idea`, `.vscode`, `.venv`, `venv`, `npm-cache`, and `.cache` from `grep` searches by appending `--exclude-dir` flags for each directory.…cessing

Add directory exclusions to local storage grep command
