centricconsulting/agent_c_framework

scripts/initial_setup.bat, scripts/initial_setup.sh, src/agent_c_core/pyproject.toml, src/agent_c_reference_apps/src/agent_c_reference_apps/agent_c_gradio.py
This pull request includes several updates to the virtual environment setup scripts, dependency versions, and the `agent_c_gradio.py` script. The most important changes include fixing the virtual environment creation command, updating the `openai` dependency version, and removing unused command-line arguments and related code in the `agent_c_gradio.py` script.
* [`scripts/initial_setup.bat`](diffhunk://#diff-9f0788522d27598f85ee067fbc160a216a9356615e2117c4f2672f8256de9735L17-R17): Fixed the virtual environment creation command to use the correct syntax (`python -m venv .venv`).
* [`scripts/initial_setup.sh`](diffhunk://#diff-4c93955ef4d8c9650aef19be7fd7da249d9160dffbb287ef04c4f906c57d1948L16-R16): Fixed the virtual environment creation command to use the correct syntax (`python -m venv …
=> more fixes from the seperaation

scripts/fetch_latest.sh
Add a bash version of fetch_latest
=> Add mac/linux version of fetch_latest

src/agent_c_reference_apps/src/agent_c_reference_apps/util/chat_commands.py
Added the !? and !help command that will print at the cli
=> Added !? and !help for getting commands

src/agent_c_core/pyproject.toml, src/agent_c_core/src/agent_c/agents/base.py, src/agent_c_core/src/agent_c/agents/claude.py, src/agent_c_core/src/agent_c/agents/gpt.py, src/agent_c_core/src/agent_c/models/chat_event.py, src/agent_c_core/src/agent_c/toolsets/tool_chest.py, src/agent_c_reference_apps/pyproject.toml, src/agent_c_reference_apps/src/agent_c_reference_apps/agent_c_gradio.py, src/agent_c_tools/pyproject.toml, src/my_agent_c/pyproject.toml
-  Brings the ClaudeAgent up to the latest API  version.  **tool use has not been completed  yet** but since chatting was broke I wanted to get this part out.
- Stop reason is now included in the event stream
- Token usage is now included in the event stream for Claude on message end events
-  Both Claude and GPT now correctly signal interaction start/stop, message start /stop and completion start/stop
- Updated all the TOML files to have the correct license listed.
This pull request includes several changes to the `agent_c_core`, `agent_c_reference_apps`, and `agent_c_tools` packages. The most important changes involve updating dependencies, enhancing the `ClaudeChatAgent` class, and adding new callback methods.
Dependency Updates:
* Updated the version of `agent_c-core` to `0.1.2` and …
=> Cluade love

src/agent_c_core/src/agent_c/agents/base.py, src/agent_c_core/src/agent_c/agents/claude.py, src/agent_c_core/src/agent_c/agents/gpt.py, src/agent_c_reference_apps/src/agent_c_reference_apps/ui/gradio_ui.py
This pull request includes several changes to improve the functionality of the `agent_c_core` and `agent_c_reference_apps` modules. The most important changes include the addition of asynchronous function calling, enabling tool usage for the Claude agent, and refactoring the initialization of chat agents.
* [`src/agent_c_core/src/agent_c/agents/base.py`](diffhunk://#diff-05d594b58857c6a5387e2d9eb11eee0f362be65f9681840f327422756c820a77R273-R296): Added a new method `_call_function` to call functions asynchronously using the `Toolset` class.
* [`src/agent_c_core/src/agent_c/agents/claude.py`](diffhunk://#diff-d74867587f97368abcc0acaafc2f218509185212937c61d43c07a7fc5b791876R227-R250): Added the method `__tool_calls_to_messages` to handle tool calls and convert them to messages.
* …
=> Tool use for Claude now works

src/agent_c_core/src/agent_c/agents/base.py, src/agent_c_core/src/agent_c/agents/claude.py, src/agent_c_core/src/agent_c/agents/gpt.py, src/agent_c_core/src/agent_c/models/audio_input.py, src/agent_c_core/src/agent_c/models/events/chat.py, src/agent_c_core/src/agent_c/models/image_input.py, src/agent_c_core/src/agent_c/toolsets/tool_set.py, src/agent_c_reference_apps/src/agent_c_reference_apps/ui/audio_playback_worker.py, src/agent_c_reference_apps/src/agent_c_reference_apps/ui/console_chat_ui.py, src/agent_c_reference_apps/src/agent_c_reference_apps/ui/gradio_ui.py
The code in this changeset, except for the new ImageInput helper, is to support upcoming features in Open AI models.  This is bleeding edge and while I don't expect them to change anything major, the final implementation may end up being slightly different. the only Open AI model supporting this modality is gpt-4o-audio-preview.
- Nerw AudioInput class for sending audio in the message array.  
-  AudioInput.from_file helper can load files from disk / gradio
- the chat method now supports an `audio` parameter which can contain a list of AudioInputs.
- ImageInput.from_file helper added
- Gradio client now accepts audio file uploads.
- Audio output support is there but still wip.
-  Setting the `voice` to one of the Open AI voices (alloy, ash, coral, echo, fable, onyx, nova, sage and …
=> Support for audio input with GPT agents

src/agent_c_core/pyproject.toml, src/agent_c_core/src/agent_c/agents/base.py, src/agent_c_core/src/agent_c/agents/gpt.py, src/agent_c_core/src/agent_c/toolsets/tool_set.py, src/agent_c_core/src/agent_c/util/oai_audio.py, src/agent_c_reference_apps/src/agent_c_reference_apps/agent_c_gradio.py, src/agent_c_reference_apps/src/agent_c_reference_apps/ui/console_chat_ui.py, src/agent_c_reference_apps/src/agent_c_reference_apps/ui/gradio_ui.py
- Stole the async player from Open AI to use for AudioDeltaEvents in the reference app
- Added support for saving audio ids to the message history so the agent would talk more than once.  Have ideas on how to fix this a different way but this works for now.
- Fixed a bug that caused system prompts to get duplicated on each completion....
This pull request introduces several significant changes to the `agent_c_core` and `agent_c_reference_apps` modules, focusing on audio handling, session management, and configuration improvements. The most important changes include the addition of new audio handling capabilities, modifications to session management methods, and updates to configuration options for voice output.
* [`src/agent_c_core/src/agent_c/util/oai_audio.py`](diffhunk://#diff-6b08cf766 …
=> Audio modallity fixes and system prompt bug fix

src/agent_c_core/src/agent_c/agents/gpt.py, src/agent_c_reference_apps/pyproject.toml, src/agent_c_reference_apps/src/agent_c_reference_apps/ui/gradio_ui.py, src/agent_c_reference_apps/src/agent_c_reference_apps/util/chat_commands.py
This pull request includes various improvements and fixes across multiple files in the `agent_c_core` and `agent_c_reference_apps` directories. The most important changes include enhancements to user input handling, dependency updates, and minor bug fixes.
* [`src/agent_c_core/src/agent_c/agents/gpt.py`](diffhunk://#diff-0b0b2a2155f664049de21c3c667705f1c11a5613fc2949087029caaff07e36cfL77-R79): Modified `_generate_multi_modal_user_message` to ensure `user_input` is added to `contents` only if it is not empty or `None`.
* [`src/agent_c_reference_apps/src/agent_c_reference_apps/ui/gradio_ui.py`](diffhunk://#diff-d5b981a8dfcdbe0d87d7dea65f9a6a8ae5a0b9c5bd938caf9c1fdc1a320fea29R218-R220): Added a check to initialize `history` as an empty list if it is `None` in `add_user_input`.
* …
=> Remove hardcoding of the voice

src/agent_c_core/src/agent_c/agents/base.py
This pull request includes an update to the `src/agent_c_core/src/agent_c/agents/base.py` file to enhance session management and message handling in the `_construct_message_array` method.
Enhancements to session management and message handling:
* [`src/agent_c_core/src/agent_c/agents/base.py`](diffhunk://#diff-05d594b58857c6a5387e2d9eb11eee0f362be65f9681840f327422756c820a77R217-R220): Added logic to save the user message to the session manager, considering multimodal messages.
=> It helps to save the user messages to the history

docker_stack/NEW_README.md, docker_stack/docker-compose.yml, docker_stack/example.env, example.env, src/agent_c_reference_apps/src/agent_c_reference_apps/react_fastapi/backend/backend_app/agent_manager.py, src/agent_c_reference_apps/src/agent_c_reference_apps/react_fastapi/backend/backend_app/reactjs_agent.py, src/agent_c_reference_apps/src/agent_c_reference_apps/react_fastapi/backend/main.py, src/agent_c_reference_apps/src/agent_c_reference_apps/react_fastapi/backend/util/logging_utils.py
Creating a shared logger
Adding Weaviate back in - Only use if you know what you're doing
=> Adding Weaviate back in

scripts/install_deps.sh, src/agent_c_core/src/agent_c/agents/gpt.py, src/agent_c_core/src/agent_c/models/chat_history/chat_memory.py
This pull request includes several changes to improve the setup instructions, refine the interaction setup process, and add a new property to the `ChatMemory` class.
* [`scripts/install_deps.sh`](diffhunk://#diff-c3ff4e129c54b291da6bdad23c8664c34a78325e7c02e8c13404041836bb82d6L13-R13): Updated the virtual environment activation command from `venv/bin/activate` to `.venv/bin/activate` to reflect the correct directory structure.
* [`src/agent_c_core/src/agent_c/agents/gpt.py`](diffhunk://#diff-0b0b2a2155f664049de21c3c667705f1c11a5613fc2949087029caaff07e36cfL122-R122): Removed the default assignment of `tool_choice` to 'none' when no functions are provided.
* [`src/agent_c_core/src/agent_c/models/chat_history/chat_memory.py`](diffhunk://#diff-d3d073ff088219e76d65768d9c922e5c073ba0d85ce4587929 …
=> Fix a handful of buglets

src/agent_c_core/src/agent_c/agents/base.py, src/agent_c_core/src/agent_c/agents/gpt.py, src/agent_c_core/src/agent_c/models/input/audio_input.py, src/agent_c_core/src/agent_c/prompting/basic_sections/env_info.py, src/agent_c_reference_apps/src/agent_c_reference_apps/agent_c_cli.py, src/agent_c_reference_apps/src/agent_c_reference_apps/react_fastapi/backend/backend_app/reactjs_agent.py, src/agent_c_reference_apps/src/agent_c_reference_apps/ui/console_chat_ui.py, src/agent_c_reference_apps/src/agent_c_reference_apps/ui/gradio_ui.py
- Added a path to recognize voice modality models that don't use voice tools  yet in the env info section
- Add yet another workaround for Open AI messing with tool calls
- Generate transcripts for voice input so we can store them in the memory for now.
This pull request includes several changes to enhance the handling of audio inputs and improve the voice mode functionality across various components. The most important changes include adding support for audio transcription, updating the `EnvironmentInfoSection` to include an agent voice attribute, and modifying the prompt metadata to include the agent voice.
Enhancements to audio input handling:
* [`src/agent_c_core/src/agent_c/agents/base.py`](diffhunk://#diff-05d594b58857c6a5387e2d9eb11eee0f362be65f9681840f327422756c820a77L220-R225): …
=> Voice mode tweaks + Open AI fix

README.md, scripts/initial_setup.bat, scripts/initial_setup.sh
It was very painful for a couple of users to get setup. Based on helping them, I updated the instructions to be a bit clearer.
=> Updated README.md and install scripts after helping more users

.dockerignore, dockerfiles/Dockerfile.dev, example.env, src/agent_c_core/src/agent_c/util/oai_audio.py
- cleaned up example env file
- added a docker file for the entire project
- fixed an issue with the oia player when there are no sound cards on the machine
--- 
This pull request includes several changes to the project, focusing on Docker configuration, environment variable updates, and error handling improvements in the audio player utility.
* Added a `.dockerignore` file to exclude unnecessary files and directories from the Docker context, such as version control files, Python cache files, and environment files.
* Created a new `Dockerfile.dev` to set up a development environment with Python, Node.js, and necessary dependencies. This includes setting environment variables and exposing a port for the application.
* Updated the `example.env` file to reorganize and clean up the …
=> Preliminary Dockerfile

.dockerignore, dockerfiles/README.md, dockerfiles/api.Dockerfile, dockerfiles/docker-compose.yml, dockerfiles/frontend.Dockerfile, dockerfiles/web_api_docker_start.bat, dockerfiles/web_api_docker_start.sh
This pull request includes several changes to improve the Docker setup and documentation for the project. The most important changes include updates to the `.dockerignore` file, the addition of new Dockerfiles for the API and frontend, and updates to the `docker-compose.yml` file to configure the services. Additionally, the documentation has been updated to reflect these changes.
* [`.dockerignore`](diffhunk://#diff-2f754321d62f08ba8392b9b168b83e24ea2852bb5d815d63e767f6c3d23c6ac5L4-R53): Updated to include more directories and files that should be ignored by Docker, such as build artifacts, environment files, and IDE-specific files.
* [`dockerfiles/api.Dockerfile`](diffhunk://#diff-158a1dffd1eea9c866e9b45df11703f291fd1d05f7f35f12c527d3e1b05244afR1-R66): Added a new Dockerfile to set up …
=> Web docker

.gitignore
.DS_Store
.python-version
node_modules
=> Pulling in gitignore changes from framework

.github/workflows/tagged-docker-build-and-push.yml, README.md, dockerfiles/agent_c.config.example, dockerfiles/docker-compose.yml, dockerfiles/docker-compose_dev.yml, dockerfiles/start_agent_c.bat, dockerfiles/start_agent_c.sh, dockerfiles/view_agent_c.bat, dockerfiles/view_agent_c.sh, dockerfiles/web_api_docker_start.bat, dockerfiles/web_api_docker_start.sh, src/agent_c_api_ui/agent_c_api/src/agent_c_api/api/v1/personas.py
- Add a new compose file that uses the prebuilt images from GitHub for non-developers to use
-  This works slightly differently than developer mode and uses the user home folder for the configuration, images and local personas
- Had Claude go over the README to add documentation for this change as well as clean up the doc for new developers.
- Modified the API backed for finding the personas, to also look in sub folders.
- The new compose file leverages this to add local personas without blowing away the "stock" ones or requiring duplicate copies.
---
This pull request includes significant updates to the `Agent C Framework` documentation, configuration, and Docker setup to improve usability and streamline the development process. The most important changes include a comprehensive overhaul …
=> New compose

.github/workflows/main-docker-build-and-push.yml, dockerfiles/api.Dockerfile, dockerfiles/start_agent_c.bat, src/agent_c_api_ui/agent_c_api/pyproject.toml, src/agent_c_core/pyproject.toml
This pull request includes several updates to Docker configurations, dependency management, and build processes. The most important changes focus on improving the Docker setup and updating dependencies for better functionality.
* [`.github/workflows/main-docker-build-and-push.yml`](diffhunk://#diff-3db748f55b3db39372c7ab5180021da288e8e4e875fa3644787e4e54024e0784L46-L58): Removed the build and push steps for the Framework image, streamlining the workflow.
* [`dockerfiles/api.Dockerfile`](diffhunk://#diff-158a1dffd1eea9c866e9b45df11703f291fd1d05f7f35f12c527d3e1b05244afR6): Added a new directory creation step for `agent_c_api_ui` and updated the source code copy commands to include `agent_c_core`, `agent_c_tools`, and `agent_c_api_ui/agent_c_api`. …
=> Slim down the docker container size

src/agent_c_api_ui/agent_c_api/pyproject.toml, src/agent_c_core/pyproject.toml, src/agent_c_reference_apps/pyproject.toml, src/agent_c_tools/pyproject.toml
This pull request includes version updates for several components within the Agent C project. The updates ensure compatibility and improvements across the different parts of the project.
Version updates:
* [`src/agent_c_api_ui/agent_c_api/pyproject.toml`](diffhunk://#diff-388ec42cdffc394231601193c6143c36e10c8aaa1b962b229e1ad527b803fe94L7-R11): Updated `agent_c-core` and `agent_c-tools` dependencies to version `0.1.3` and the project version to `0.2.0`.
* [`src/agent_c_core/pyproject.toml`](diffhunk://#diff-76974589e64d56ea3dd561ad76276387e14b3016e8fdc106bf6288f890b0e5b4L8-R8): Updated the project version to `0.1.3`.
* [`src/agent_c_reference_apps/pyproject.toml`](diffhunk://#diff-3794f65909e68f4d1302f622f62ccb20de491100c77cd1cbd4969fa23d40adf3L6-R7): Updated `agent_c-core` and …
=> Bump version numbers to test the workflow again

src/agent_c_api_ui/agent_c_api/src/agent_c_api/api/v1/chat.py, src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_bridge.py, src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_manager.py
This pull request includes changes to improve error logging across multiple files in the `agent_c_api` module. The most significant changes involve adding detailed error type and traceback information to the logs.
Error logging improvements:
* [`src/agent_c_api_ui/agent_c_api/src/agent_c_api/api/v1/chat.py`](diffhunk://#diff-5f2c534adf5880d7ea4b1e24c25926ebdfaa4d9fe1c7243043bacc222d10ac8bR1-R2): Added traceback import and enhanced error logging in the `event_stream` function to include error type and traceback. [[1]](diffhunk://#diff-5f2c534adf5880d7ea4b1e24c25926ebdfaa4d9fe1c7243043bacc222d10ac8bR1-R2) [[2]](diffhunk://#diff-5f2c534adf5880d7ea4b1e24c25926ebdfaa4d9fe1c7243043bacc222d10ac8bL40-R45)
* [`src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_bridge.py`](diffhunk://#diff-28 …
=> fix an issue draining the queue, and imrpvoe some loging

src/agent_c_api_ui/agent_c_api/src/agent_c_api/api/v1/llm_models/agent_params.py, src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_bridge.py, src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_manager.py
This pull request includes several changes to the `agent_c_api` module, primarily focused on renaming the `custom_persona_text` attribute to `custom_prompt` across various files and functions. Additionally, some error logging improvements have been made.
Renaming `custom_persona_text` to `custom_prompt`:
* [`src/agent_c_api_ui/agent_c_api/src/agent_c_api/api/v1/llm_models/agent_params.py`](diffhunk://#diff-bdec487896591407592eb453eaab13dad217ecd6b6d76db16b4a91a09bd30727L80-R85): Updated the key in the `to_additional_params` method to `custom_prompt`.
* [`src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_bridge.py`](diffhunk://#diff-28bc5184f60b617647c44cd86d7e90885fee567cc04bad4bdf9ffda2f4e533d7L47-R47): Renamed `custom_persona_text` to `custom_prompt` in the `AgentBridge` class …
=> Fixing getting the persona prompt to make it to the models.

src/agent_c_api_ui/agent_c_api/src/agent_c_api/api/v1/chat.py, src/agent_c_api_ui/agent_c_api/src/agent_c_api/config/model_configs.json, src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_bridge.py, src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/util/logging_utils.py, src/agent_c_api_ui/agent_c_react_client/src/components/chat_interface/ChatInterface.jsx, src/agent_c_api_ui/agent_c_react_client/src/components/rag_interface/Search/SearchForm.jsx, src/agent_c_api_ui/agent_c_react_client/src/components/rag_interface/Search/SearchResults.jsx
This pull request includes several changes to improve error handling, enhance search functionality, and add new configuration options. The most important changes are grouped into error handling improvements, configuration updates, and search functionality enhancements.
* Added error logging in `event_stream` function in `chat.py` to log errors in stream responses.
* Introduced new handler methods `convert_to_string`, `_handle_message`, `_handle_tool_select_delta`, and `_handle_tool_call_delta` in `agent_bridge.py` to handle various events and errors.
* Updated `consolidated_streaming_callback` in `agent_bridge.py` to include new event types and avoid adding certain events to the stream queue.
* Enhanced `ChatInterface` component in `ChatInterface.jsx` to handle and display error messages …
=> Rag changes

.gitignore
=> Ignore node modules and lock files

dockerfiles/docker-compose_dev.yml, src/agent_c_api_ui/agent_c_api/pyproject.toml, src/agent_c_api_ui/agent_c_api/src/agent_c_api/api/v1/agent.py, src/agent_c_api_ui/agent_c_api/src/agent_c_api/api/v1/chat.py, src/agent_c_api_ui/agent_c_api/src/agent_c_api/api/v1/files.py, src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_bridge.py, src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_manager.py, src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/file_handler.py, src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/util/logging_utils.py, src/agent_c_api_ui/agent_c_react_client/src/components/chat_interface/ChatInterface.jsx, src/agent_c_core/src/agent_c/agents/base.py, src/agent_c_core/src/agent_c/agents/claude.py, src/agent_c_core/src/agent_c/agents/gpt.py, src/agent_c_core/src/agent_c/models/input/file_input.py
This pull request introduces several significant changes to the `agent_c_api_ui` project, focusing on enhancing file handling capabilities, updating dependencies, and improving logging. The most important changes include adding support for file uploads and processing, modifying endpoints to handle file-related operations, and updating dependencies.
* [`src/agent_c_api_ui/agent_c_api/src/agent_c_api/api/v1/files.py`](diffhunk://#diff-f4498549e05533d4c3bd38cca388551fa69082b0e3c9cb8c61151e3819b650faL1-R237): Added endpoints for uploading, listing, retrieving, and deleting files, along with background tasks for cleaning up expired files and processing uploaded files.
* [`src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_bridge.py`](diffhunk://#diff-28bc5184f60b617647c44cd86d7e90885fee5 …
=> Session files - we can now insert file content inline.  Supports image upload.  Base for audio in place.

personas/suno_sam.md, src/agent_c_api_ui/agent_c_react_client/vite.config.js
This pull request includes significant changes to the `personas/suno_sam.md` file to define the persona of "Suno Sam" and provide detailed guidelines for crafting lyrics and prompts for Suno.ai. Additionally, there is a small configuration update in the `vite.config.js` file to enhance the server setup.
* [`personas/suno_sam.md`](diffhunk://#diff-8611ad78a157a31b742028c6f0c75729ed531c771b53fbca073ed2fdae8c7ebeR1-R177): Added a comprehensive persona description for "Suno Sam," including core identity, critical rules, formatting techniques, style guidance, advanced techniques, song structure best practices, workflow recommendations, and error handling.
* [`src/agent_c_api_ui/agent_c_react_client/vite.config.js`](diffhunk://#diff-ce4bd16eac737d3ff09b27df27f8de992a8794257f4839d2c065d8487ea107f …
=> Add sunno sam persona

dockerfiles/docker-compose.yml, dockerfiles/start_agent_c.sh, dockerfiles/start_agent_c_local.bat, docs/workspace_technical_guide.md, docs/workspace_user_guide.md, scripts/create-framework-symlink-unix.sh, scripts/create-framework-symlink.bat, src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_bridge.py, src/agent_c_reference_apps/src/agent_c_reference_apps/agent_c_cli.py, src/agent_c_reference_apps/src/agent_c_reference_apps/ui/gradio_ui.py, src/agent_c_tools/src/agent_c_tools/tools/workspaces/local_storage.py, src/agent_c_tools/src/agent_c_tools/tools/workspaces/tool.py
* Added Docker Compose configuration to map host project source to the "project" workspace
* Enhanced workspace tool security by enforcing relative paths only
* Improved symlink handling within workspace operations
* Added comprehensive user documentation for workspaces
* Developers can now edit source code directly on their host machine while seeing changes immediately in the container
* Prevents potential path traversal issues by restricting workspace operations to relative paths
* More reliable file operations when dealing with symbolic links
* Better user experience through clear documentation on workspace usage patterns and best practices
* Docker Compose volume mappings preserve file permissions between host and container
* Path validation occurs before any file operations to ensure …
=> Workspace improvments

docs/workspace_scratchpads.md, src/agent_c_tools/src/agent_c_tools/tools/workspaces/prompt.py
This change updates the model instructions for the Workspace tool to allow "scratch pads" for agents.  See the doc on them in the docs folder for details
--- 
This pull request includes changes to the `WorkspaceSection` class in the `src/agent_c_tools/src/agent_c_tools/tools/workspaces/prompt.py` file. The changes aim to improve the clarity and usability of the workspace tools by updating the template text.
Improvements to workspace tools:
* Updated the template text to provide clearer instructions and additional information about workspace rules and procedures. The new text includes a more detailed description of workspace paths, write operations, and the concept of a scratchpad.
=> QOL: Scratchpads

scripts/start_api.bat, scripts/start_fe.bat, src/agent_c_api_ui/agent_c_api/src/agent_c_api/api/v1/llm_models/agent_params.py, src/agent_c_api_ui/agent_c_api/src/agent_c_api/main.py, src/agent_c_reference_apps/src/agent_c_reference_apps/agent_c_cli.py
- CLI now uses dynamic persona sections like the rest of the reference apps
- added started up script for the API and Frontend running locally
- Modified the main.py  @justjoehere  put in for debugging so I could actually use if for debugging
- Add a model config to the base model for the API so the warning about using `model_name`  goes away
-- 
This pull request includes several changes to improve the startup scripts, update dependencies, and enhance functionality in the `agent_c_api` and `agent_c_reference_apps` modules. The most important changes include the addition of startup scripts for the API and frontend, updates to import statements, and modifications to the agent initialization and prompt metadata.
* [`scripts/start_api.bat`](diffhunk://#diff-4e17cd2b2d3834e001e324b7ba37f797ccb …
=> A bunch of minor ixes

src/agent_c_core/src/agent_c/agents/claude.py
This pull request includes several changes to the `chat` method in the `claude.py` file to improve the handling of escape sequences and the processing of JSON deltas. Additionally, some static methods were introduced and minor refactoring was done to improve code readability and functionality.
Improvements to escape sequence handling and JSON delta processing:
* Added `process_escapes` static method to handle escape sequences in text.
* Introduced new states (`tts_inactive`, `tts_waiting`, `tts_emitting`) and variables (`think_tool_state`, `think_partial`, `think_escape_buffer`) to manage the processing of JSON deltas. [[1]](diffhunk://#diff-d74867587f97368abcc0acaafc2f218509185212937c61d43c07a7fc5b791876R140-L143) [[2]](diffhunk://#diff-d74867587f97368abcc0acaafc2f218509185212937c61d43c07 …
=> A little hack to make think tool usage stream like reasoning tokens

personas/boto3_tool_coder.md, personas/code_archaeologist.md, personas/conway.md, personas/csharp_builder.md, personas/doc_explorer.md
This PR includes several "Conway class" agents.  The `conway.md` agent is the one that really launched this generation.  The first version of Conway was something I threw together quickly using pieces of different agents I had bee working on into one agent.  It worked better out of he gate than any development agent I had seen  I've spent the past two weeks refining them.  I'm FAR from done but these are already so capable I'm embarrassed to call anything I've done prior an agent.
- Don't let these agents fool you, this is NOT a coding agent class, this is a generic agent class I turned into coding agents because that's what I needed.  @justjoehere has used this same class of agent for insanely complicated business tasks.
- I'll be covering this agent class in office hours this week.
- …
=> Add several conway class agents as references

src/agent_c_api_ui/agent_c_react_client/src/components/chat_interface/ChatInterface.jsx
This pull request includes significant changes to the `ChatInterface` component in `src/agent_c_api_ui/agent_c_react_client/src/components/chat_interface/ChatInterface.jsx` to remove audio-related functionalities. The most important changes include the removal of audio recording and playback features, as well as the associated state management and helper functions.
Removal of audio-related functionalities:
* Removed imports for `AudioRecorder`, `AudioPlayer`, and `isModelVoiceCapable` from `ChatInterface.jsx`.
* Removed state variables `lastAudioResponse` and `audioResponsePlaying` that were used to manage audio responses.
* Removed the `handleAudioRecorded` function that handled audio recording completion and sent the audio data to the API.
* Removed the audio player display logic that …
=> Emergency removal of WIP audio code

personas/bob_the_builder.md, personas/chetan.md, personas/thinking_tim.md
This pull request focuses on updating and expanding the guidelines for agent personas, specifically for `Bob the Builder` and adding a new persona, `Chetan`. The changes emphasize the importance of reflection, structured thinking, and adherence to specific rules and standards for different types of agents.
* **Core Identity and Purpose**: Updated the name to "Bobb the steward - Ai Agent expert" and added a reminder about using the think tool for reflection.
* **Interaction Guidelines**: Introduced critical interaction guidelines emphasizing reflection and structured thinking during multi-step processes.
* **Persona Structure**: Revised the sections to include thinking reminders, special rules, and detailed instructions for tool requirements and error handling.
* **Special Rules for …
=> Bob upgrade to conway

src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_bridge.py, src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_manager.py, src/agent_c_api_ui/agent_c_react_client/src/components/chat_interface/ChatInterface.jsx, src/agent_c_api_ui/agent_c_react_client/src/components/chat_interface/MediaMessage.jsx, src/agent_c_api_ui/agent_c_react_client/src/components/chat_interface/ThoughtDisplay.jsx, src/agent_c_core/src/agent_c/toolsets/tool_set.py, src/agent_c_tools/src/agent_c_tools/tools/full.py, src/agent_c_tools/src/agent_c_tools/tools/markdown_to_html_report/__init__.py, src/agent_c_tools/src/agent_c_tools/tools/markdown_to_html_report/ignore-original utility code/generate-markdown-viewer-enhanced.py, src/agent_c_tools/src/agent_c_tools/tools/markdown_to_html_report/ignore-original utility code/markdown-viewer-template-enhanced.html, src/agent_c_tools/src/agent_c_tools/tools/markdown_to_html_report/markdown-viewer-template.html, src/agent_c_tools/src/agent_c_tools/tools/markdown_to_html_report/tool.py, src/agent_c_tools/src/agent_c_tools/tools/think/tool.py, src/agent_c_tools/src/agent_c_tools/tools/workspace/local_storage.py, src/agent_c_tools/src/agent_c_tools/tools/workspace/tool.py
This pull request introduces several changes across multiple files to enhance the functionality of markdown handling and improve the user interface. The most important changes include adding a new tool for converting markdown to HTML reports, updating the UI components to handle markdown content, and adding utility functions for processing markdown files.
* [`src/agent_c_core/src/agent_c/toolsets/tool_set.py`](diffhunk://#diff-f62940b76b30c07afce8cdbc1201380588567e659bbca253f8f2664a0691d818R85-R115): Added a `_format_markdown` method to format markdown strings for proper rendering and integrated this formatting into the `_raise_render_media` method to ensure markdown content is correctly formatted before being processed. [[1]](diffhunk://#diff-f62940b76b30c07afce8cdbc1201380588567e659bbca2 …
=> Markdown viewer tool

src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_bridge.py, src/agent_c_core/src/agent_c/agents/base.py, src/agent_c_core/src/agent_c/agents/claude.py, src/agent_c_core/src/agent_c/agents/gpt.py, src/agent_c_core/src/agent_c/util/logging_utils.py, src/agent_c_core/src/agent_c/util/session_logger.py, src/agent_c_tools/src/agent_c_tools/tools/mermaid_chart/tool.py, src/agent_c_tools/src/agent_c_tools/tools/random_number/tool.py, src/agent_c_tools/src/agent_c_tools/tools/weather/util/client.py
This PR refactors gpt.py to work wtih OpenAI and Azure OpenAI.  It also address logs folder creation, and better handles session creation.  Some minor tweaks to tools as well.
=> Gpt 4o streaming bug

src/agent_c_api_ui/agent_c_api/src/agent_c_api/api/v1/interactions/services/interaction_service.py, src/agent_c_api_ui/agent_c_api/src/agent_c_api/config/env_config.py, src/agent_c_api_ui/agent_c_api/src/agent_c_api/main.py
This pull request introduces logging enhancements, error handling improvements, and optional profiling capabilities to the `InteractionService` and the main application. The most important changes include adding structured logging, improving error reporting, and integrating a profiling middleware for performance analysis.
* Added a `LoggingManager` to the `InteractionService` for structured logging and debug messages, such as the number of session directories and session directory paths.
* Replaced silent error handling with detailed log messages for invalid metadata files, JSON parsing errors, and file reading issues in `list_sessions`. [[1]](diffhunk://#diff-fb6bc9d7bfe4c18745aad14580d265fdf1e507fe89978fba57156d0f0033b633L56-R67) …
=> Tweaking sessions

src/agent_c_api_ui/agent_c_api/src/agent_c_api/api/v1/tools.py, src/agent_c_api_ui/agent_c_api/src/agent_c_api/main.py
This pull request simplifies the logging and configuration setup, removes unused imports and code, and improves the clarity of log messages. The key changes include the removal of optional module handling, the removal of profiling middleware setup, and updates to log messages for better readability.
* Updated log messages in `tools.py` to provide clearer descriptions when optional tools are not installed.
* Ensured FastAPI logs use the custom logging configuration by clearing and reassigning handlers.
* Added comments to clarify the purpose of external logger configuration and FastAPI logger setup. [[1]](diffhunk://#diff-fffd1f34d40f8c121df456a26ee0c83cde4d3facc697ed47c94a48e053230712R27) [[2]](diffhunk://#diff-fffd1f34d40f8c121df456a26ee0c83cde4d3facc697ed47c94a48e053230712R41)
* Removed …
=> Perf tweak

src/agent_c_api_ui/agent_c_api/src/agent_c_api/config/model_configs.json
This pull request updates the `model_configs.json` file to include new GPT-4.1 model variants and refines the descriptions of existing models. The most significant changes involve adding detailed configurations for the new models and improving clarity in model descriptions.
* Added configurations for `gpt-4.1`, `gpt-4.1-mini`, and `gpt-4.1-nano` models, including their parameters, capabilities, and allowed input types. These models are designed for complex tasks and support multi-modal inputs.
* Updated the description of the `gpt-4o` model to remove the word "Latest" for clarity.
* Updated the description of the `gpt-4o-audio-preview` model to remove the word "Latest" for consistency with other descriptions.
=> Add GPT-4.1

src/agent_c_api_ui/agent_c_react_client/src/components/chat_interface/ToolSelector.jsx
This pull request introduces a small but significant improvement to the `ToolSelector` component in the `chat_interface` of the `agent_c_react_client`. The change enhances the user interface by adding support for dark mode styling.
* [`src/components/chat_interface/ToolSelector.jsx`](diffhunk://#diff-ee4d2798dac2c886bb4cd4cec23f1bcd85669df0ade3ee41f66bfa9cb07282bcL76-R76): Updated the `ToolCategory` component to include dark mode styles for both active and non-active states, ensuring better visual consistency in dark mode.
=> Fix tool name hover effect

src/agent_c_api_ui/agent_c_react_client/src/components/ui/theme-toggle.jsx, src/agent_c_api_ui/agent_c_react_client/src/contexts/ThemeProvider.jsx
This pull request introduces a theme toggle feature and ensures dynamic theme application based on user selection or system preferences. The changes include adding a `ThemeToggle` component and a `ThemeProvider` to manage and apply themes.
* **`ThemeToggle` Component**: Added a new `ThemeToggle` component that provides buttons to switch between light mode, dark mode, and system theme. It uses the `SessionContext` to manage the current theme and updates the UI accordingly. (`src/components/ui/theme-toggle.jsx`, [src/agent_c_api_ui/agent_c_react_client/src/components/ui/theme-toggle.jsxR1-R43](diffhunk://#diff-6453d0f68865fdff7edd23b6ccabaf50e1965c1e75f2d5ac9502f75dcb4c4a5dR1-R43))
* **`ThemeProvider` Component**: Introduced a `ThemeProvider` component that dynamically applies the selected …
=> missed these fles

src/agent_c_core/src/agent_c/util/session_logger.py
This pull request enhances the `log_event` method in `src/agent_c_core/src/agent_c/util/session_logger.py` to improve event processing and logging. The changes include better handling of different event types and minor cleanup of the logging logic.
Improvements to event processing:
* Enhanced the `log_event` method to handle various event types more robustly. It now processes Pydantic models using `model_dump`, attempts to parse strings as JSON, and falls back to using the event as-is for other types like dictionaries, lists, or primitives. (`[src/agent_c_core/src/agent_c/util/session_logger.pyL77-R90](diffhunk://#diff-f32905c118185516c884d9197f17d2095720c7d9b9bf4b4d09d7dbb55e8c8b7eL77-R90)`)
Code cleanup:
* Removed an unnecessary blank line after writing the log entry to the file, …
=> Enable handling of json, dict, list to avoid double encoding.

personas/_do_nothing.md, src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/util/logging_utils.py, src/agent_c_api_ui/agent_c_api/src/agent_c_api/main.py, src/agent_c_tools/src/agent_c_tools/tools/dynamics/prompt.py, src/agent_c_tools/src/agent_c_tools/tools/dynamics/tool.py, src/agent_c_tools/src/agent_c_tools/tools/dynamics/util/dynamics_api.py, src/agent_c_tools/src/agent_c_tools/tools/dynamics/util/dynamics_dictionary.py, src/agent_c_tools/src/agent_c_tools/tools/workspace/tool.py, src/agent_c_tools/src/agent_c_tools/tools/workspace/util/replace_strings_helper.py
This pull request introduces several enhancements and fixes across multiple modules, focusing on improving the functionality and usability of the Dynamics CRM toolset, refining logging, and updating documentation. The most significant changes include adding support for specifying additional and override fields in Dynamics CRM queries, improving file handling and user feedback for saved data, and fixing minor typos and formatting issues.
* Added support for specifying `additional_fields`, `override_fields`, and `additional_expand` parameters in the `get_entities` method to allow more granular control over the fields and relationships included in query responses. (`[[1]](diffhunk://#diff-9adf02f8ad603fe2dd8e3438530690c23098a71fb8f915d55414215ad29db70aR110-R137)`, …
=> Tweak dynamics

src/agent_c_api_ui/agent_c_react_client/src/components/AppSidebar.jsx, src/agent_c_api_ui/agent_c_react_client/src/components/Layout.jsx, src/agent_c_api_ui/agent_c_react_client/src/components/chat_interface/ChatInputArea.jsx, src/agent_c_api_ui/agent_c_react_client/src/components/chat_interface/ChatInterface.jsx, src/agent_c_api_ui/agent_c_react_client/src/components/chat_interface/DragDropArea.jsx, src/agent_c_api_ui/agent_c_react_client/src/components/chat_interface/FileUploadManager.jsx, src/agent_c_api_ui/agent_c_react_client/src/components/chat_interface/SystemMessage.jsx, src/agent_c_api_ui/agent_c_react_client/src/components/chat_interface/ToolCallItem.jsx, src/agent_c_api_ui/agent_c_react_client/src/components/chat_interface/UserMessage.jsx, src/agent_c_api_ui/agent_c_react_client/src/styles/components/app-sidebar.css, src/agent_c_api_ui/agent_c_react_client/src/styles/components/chat-interface.css, src/agent_c_api_ui/agent_c_react_client/src/styles/components/layout.css
This pull request introduces several improvements and fixes to the `agent_c_api_ui` React client, focusing on file upload functionality, default prop handling, and layout adjustments. Key changes include enhancing file upload error handling and feedback, refactoring default prop declarations, and ensuring consistent layout styling for better responsiveness.
* Updated `handleFileDrop` in `ChatInterface.jsx` to process multiple files and improve file handling consistency. Added a new `checkFileProcessingStatus` function for polling file processing status. [[1]](diffhunk://#diff-6eb3567159e05664e6e9b949304ed3084b09e37b09ff7af38b30ffa4f503bc25L143-R174) [[2]](diffhunk://#diff-6eb3567159e05664e6e9b949304ed3084b09e37b09ff7af38b30ffa4f503bc25L199-R387)
* Enhanced `FileUploadManager.jsx` to …
=> Fix file uploads

src/agent_c_api_ui/agent_c_react_client/docs/components/chat-interface/clipboard-paste.md, src/agent_c_api_ui/agent_c_react_client/src/components/chat_interface/ChatInputArea.jsx, src/agent_c_api_ui/agent_c_react_client/src/components/chat_interface/ChatInterface.jsx, src/agent_c_api_ui/agent_c_react_client/src/styles/components/clipboard-paste.css, src/agent_c_api_ui/agent_c_react_client/src/styles/main.css, src/agent_c_api_ui/agent_c_react_client/vite.config.js
This pull request introduces clipboard paste functionality to the chat interface, enabling users to paste images and files directly from their clipboard. The implementation includes both frontend logic and styling changes, along with updates to documentation. Below is a summary of the most important changes:
* **Frontend Logic**:
- Added a `handlePaste` function in `ChatInputArea.jsx` to capture clipboard events, process pasted files, and trigger animations. This includes assigning default names to unnamed images and preventing text from being pasted alongside images. [[1]](diffhunk://#diff-720615e35f74141cc97ce4f026f4bd8d20d035ae260f1d4b5901db6f793c9adeR51-R111) [[2]](diffhunk://#diff-720615e35f74141cc97ce4f026f4bd8d20d035ae260f1d4b5901db6f793c9adeL71-R143)
- Introduced a …
=> You can now paste files from the clipboard

src/agent_c_api_ui/agent_c_react_client/.scratch/session_context_issues.md
This pull request adds a markdown document outlining issues and a plan for refactoring the `SessionContext` in the `agent_c_react_client` project. The document highlights previous challenges, such as missed API calls, insufficient debugging, and race conditions, and proposes a more structured approach for the next attempt.
Key additions:
* Documented previous failures in refactoring `SessionContext`, including missed API calls, lack of debugging information, overambitious debugging tools, and race conditions. (`src/agent_c_api_ui/agent_c_react_client/.scratch/session_context_issues.md`, [src/agent_c_api_ui/agent_c_react_client/.scratch/session_context_issues.mdR1-R16](diffhunk://#diff-c85fcf4b0d6edd87c4fde648f38c36f070cd28a54efaada8dddaa96b8ecc8cd4R1-R16))
* Proposed a detailed plan for …
=> Fix some issues with the agent bridge and the toolchest

personas/sandy-shadCN.md, src/agent_c_api_ui/agent_c_react_client/.gitattributes, src/agent_c_api_ui/agent_c_react_client/.npmrc, src/agent_c_api_ui/agent_c_react_client/.scratch/OLD.PersonaSelector.jsx, src/agent_c_api_ui/agent_c_react_client/.scratch/SessionContext.jsx.OLD, src/agent_c_api_ui/agent_c_react_client/.scratch/session_context_refactoring_phase_2_plan.md, src/agent_c_api_ui/agent_c_react_client/package.json, src/agent_c_api_ui/agent_c_react_client/src/services/session-api.js
This pull request introduces several changes to improve session management, enhance the user interface, and update configuration files. The key changes include adding a new `PersonaSelector` component, refactoring session management, and updating scripts and API endpoints for better compatibility and functionality.
* Added a new `PersonaSelector` component in `.scratch/OLD.PersonaSelector.jsx` to manage AI model settings, persona selection, and custom prompts through a user-friendly interface. It includes features like persona and model selection, custom prompt editing, and model parameter controls.
* Introduced a detailed plan for creating a new `SessionContext` to handle core session management in `.scratch/session_context_refactoring_phase_2_plan.md`. The plan includes creating a …
=> Context refactor 2.1

docs/developer/README_IDs.md, src/agent_c_core/src/agent_c/util/slugs.py
This pull request introduces the `MnemonicSlugs` system, a new feature for generating human-friendly, memorable identifiers, and adds significant enhancements to the corresponding implementation in the `slugs.py` file. The changes include detailed documentation, new methods for deterministic and hierarchical ID generation, and updates to improve code clarity and functionality.
* Added a comprehensive guide in `docs/developer/README_IDs.md` explaining the purpose, features, and usage of the `MnemonicSlugs` system, including examples and best practices.
* Introduced the `generate_id_slug` method for deterministic slug generation based on a seed, supporting both string and integer seeds.
* Added the `generate_hierarchical_id` method to create hierarchical IDs composed of multiple slug parts, …
=> Update Slug generation for IDs add ref doc

personas/cora-agent_c_core_dev.md, personas/cora_fastapi_dev.md, src/agent_c_api_ui/agent_c_api/.scratch/config_endpoints_test_analysis.md, src/agent_c_api_ui/agent_c_api/.scratch/config_endpoints_test_migration_plan.md, src/agent_c_api_ui/agent_c_api/.scratch/config_models_test_analysis.md, src/agent_c_api_ui/agent_c_api/.scratch/config_models_test_migration_plan.md, src/agent_c_api_ui/agent_c_api/.scratch/dependency_pattern.md, src/agent_c_api_ui/agent_c_api/.scratch/test_migration_detailed_plan.md, src/agent_c_api_ui/agent_c_api/.scratch/test_migration_session_tracker.md, src/agent_c_api_ui/agent_c_api/src/agent_c_api/api/v2/config/router.py, src/agent_c_api_ui/agent_c_api/tests/pytest.ini, src/agent_c_api_ui/agent_c_api/tests/unit/api/v2/config/conftest.py, src/agent_c_api_ui/agent_c_api/tests/unit/api/v2/config/test_endpoints.py, src/agent_c_api_ui/agent_c_api/tests/unit/api/v2/config/test_models.py
This pull request includes updates to the documentation and testing guidelines for the Agent C API, with a focus on improving clarity, organization, and test coverage. Key changes include the introduction of a standardized dependency injection pattern for FastAPI, enhancements to the test migration plan, and detailed analysis of the `test_endpoints.py` file. Additionally, various sections were reorganized to improve readability and maintainability.
* **Dependency Injection Pattern**: Introduced a standardized pattern for FastAPI dependency injection, including examples for service provider functions, service class initialization, and router endpoint dependencies. This ensures proper dependency resolution and simplifies testing.
* **ID Generation Rules**: Added detailed documentation on …
=> WIP Unit test migration 

scripts/install_deps.bat, src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_bridge.py, src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_manager.py, src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/util/logging_utils.py, src/agent_c_core/src/agent_c/agents/gpt.py, src/agent_c_core/src/agent_c/prompting/prompt_builder.py, src/agent_c_core/src/agent_c/toolsets/tool_chest.py, src/agent_c_tools/pyproject.toml, src/agent_c_tools/src/agent_c_tools/helpers/dataframe_in_memory.py, src/agent_c_tools/src/agent_c_tools/tools/__init__.py, src/agent_c_tools/src/agent_c_tools/tools/dynamics/tool.py, src/agent_c_tools/src/agent_c_tools/tools/full.py, src/agent_c_tools/src/agent_c_tools/tools/mariadb/__init__.py, src/agent_c_tools/src/agent_c_tools/tools/mariadb/tool.py
This pull request introduces several updates across multiple components of the project, focusing on bug fixes, feature enhancements, and new tool integrations. The most significant changes include a fix for an NPM installation issue, improvements to toolset initialization and management, enhanced error handling in prompt rendering, and the addition of MariaDB support.
* [`scripts/install_deps.bat`](diffhunk://#diff-de915ec606b4024bd7beb0a6bf618972b0a3fce3ff57b417627a1b5a41ba2852R34-R56): Added a workaround for an NPM bug by removing `node_modules` and `package-lock.json` before reinstalling dependencies.
* [`src/agent_c_api/core/agent_bridge.py`](diffhunk://#diff-28bc5184f60b617647c44cd86d7e90885fee567cc04bad4bdf9ffda2f4e533d7R273-R281): Updated the `update_tools` and `__init_tool_chest` …
=> Update for lag

personas/cora_fastapi_dev.md, src/agent_c_api_ui/agent_c_api/.scratch/chat_models_test_analysis.md, src/agent_c_api_ui/agent_c_api/.scratch/chat_models_test_migration_plan.md, src/agent_c_api_ui/agent_c_api/.scratch/config_services_test_analysis.md, src/agent_c_api_ui/agent_c_api/.scratch/config_services_test_fixes.md, src/agent_c_api_ui/agent_c_api/.scratch/config_services_test_migration_plan.md, src/agent_c_api_ui/agent_c_api/.scratch/test_migration_session_tracker.md, src/agent_c_api_ui/agent_c_api/docs/testing.md, src/agent_c_api_ui/agent_c_api/src/agent_c_api/api/v2/config/dependencies.py, src/agent_c_api_ui/agent_c_api/src/agent_c_api/api/v2/models/chat_models.py, src/agent_c_api_ui/agent_c_api/tests/conftest.py, src/agent_c_api_ui/agent_c_api/tests/pytest.ini, src/agent_c_api_ui/agent_c_api/tests/unit/api/v2/config/__init__.py, src/agent_c_api_ui/agent_c_api/tests/unit/api/v2/config/conftest.py, src/agent_c_api_ui/agent_c_api/tests/unit/api/v2/config/test_router.py, src/agent_c_api_ui/agent_c_api/tests/unit/api/v2/config/test_services.py, src/agent_c_api_ui/agent_c_api/tests/unit/api/v2/models/test_chat_models.py
This pull request introduces significant improvements to testing practices, test coverage, and code organization for the `Agent C API` project. Key changes include reorganizing and expanding test coverage for chat models and configuration services, addressing test reliability issues, and implementing best practices for mocking and test independence.
* Added detailed analysis of the `test_chat_models.py` file, identifying missing test coverage for conversion methods (`to_message_event`, `from_message_event`) and the `ChatResponse` model. Recommendations include reorganizing tests into classes, adding markers, and improving documentation.
* Proposed a migration plan for `test_chat_models.py`, including a new class-based structure, additional tests for missing functionality, and …
=> More unit test migration and fixing.

dockerfiles/docker-compose.yml, dockerfiles/start_agent_c.sh, src/agent_c_api_ui/agent_c_react_client/package.json
This adds the ability for linux arm based processors and was tested on Mac M2.
=> arm processor support to the docker start linux

src/agent_c_api_ui/agent_c_api/pyproject.toml, src/agent_c_api_ui/agent_c_react_client/package.json, src/agent_c_tools/src/agent_c_tools/tools/workspace_planning/tool.py
This pull request refactors several methods in the `workspace_planning` tool to simplify responses by replacing dictionary-based outputs with plain strings or YAML-formatted strings. Additionally, it includes dependency updates and minor code adjustments. Below is a summary of the most important changes:
* Simplified method return types in `tool.py` by replacing dictionary responses with either plain strings or YAML-formatted strings for better readability and consistency. This includes methods like `create_plan`, `list_plans`, `get_plan`, `create_task`, `update_task`, `get_task`, `list_tasks`, `add_lesson_learned`, `list_lessons_learned`, and `delete_task`. [[1]](diffhunk://#diff-31898117c06d69eb03a8b2fb3146b943581c64421fd3d595982762d14e781318L109-R122) …
=> Fix dependencies. Make the planning tool use fewer tokens

src/agent_c_core/src/agent_c/agents/claude.py, src/agent_c_tools/src/agent_c_tools/tools/workspace_planning/tool.py
This pull request introduces significant enhancements to the `agent_c` core and tools, focusing on improving tool handling and adding new functionality for exporting workspace plans to markdown reports. Below is a summary of the most important changes:
* Added support for handling server tool calls and responses by introducing new state fields (`server_tool_calls`, `server_tool_responses`) and extending the message history with these fields during interaction handling (`_handle_claude_stream`). [[1]](diffhunk://#diff-d74867587f97368abcc0acaafc2f218509185212937c61d43c07a7fc5b791876R234-R235) [[2]](diffhunk://#diff-d74867587f97368abcc0acaafc2f218509185212937c61d43c07a7fc5b791876R244-R247) [[3]](diffhunk://#diff-d74867587f97368abcc0acaafc2f218509185212937c61d43c07a7fc5b791876R259-R260)
* …
=> Handle the new server tool events better

docs/tools/README_BROWSER_PLAYWRIGHT.md, docs/tools/README_WORKSPACE.md, personas/tim_the_toolman-agent_tool_builder.md
This pull request introduces significant updates to the documentation for the Browser Playwright and Workspace tools, enhancing their usability and functionality. Key changes include the addition of detailed capabilities, practical use cases, advanced features, and best practices for both tools. These updates aim to improve user understanding and provide guidance for leveraging the tools effectively.
* Added a comprehensive README (`docs/tools/README_BROWSER_PLAYWRIGHT.md`) detailing the Browser Playwright Tool's capabilities, practical use cases (e.g., web automation, testing, and data extraction), configuration requirements, example interactions, API reference, and troubleshooting tips.
* Expanded the Workspace tool documentation (`docs/tools/README_WORKSPACE.md`) with new features:
- …
=> Doc updates, remove planning stuff from tims prompt

.gitignore, agent_c_config/model_configs.json, example.env, src/agent_c_core/src/agent_c/config/__init__.py, src/agent_c_core/src/agent_c/config/config_loader.py, src/agent_c_core/src/agent_c/config/model_config_loader.py, src/agent_c_core/src/agent_c/config/persona_loader.py, src/agent_c_core/src/agent_c/models/__init__.py, src/agent_c_core/src/agent_c/models/model_config/__init__.py, src/agent_c_core/src/agent_c/models/model_config/models.py, src/agent_c_core/src/agent_c/models/model_config/parameters.py, src/agent_c_core/src/agent_c/models/model_config/vendors.py
This pull request introduces significant enhancements to the configuration and model handling for the `agent_c` project, including new loaders, model definitions, and parameter structures. It also updates the `example.env` file by cleaning up unused entries and adding placeholders for new configurations. Below are the most important changes grouped by theme:
* Added `ConfigLoader` to handle general configuration file loading, including locating the configuration path dynamically. (`src/agent_c_core/src/agent_c/config/config_loader.py`)
* Introduced `ModelConfigurationLoader` to manage loading, validating, and saving model configuration data from JSON files. (`src/agent_c_core/src/agent_c/config/model_config_loader.py`)
* Added `PersonaLoader` to manage persona configurations, including …
=> New persona

src/agent_c_tools/src/agent_c_tools/docs/working_with_files.md, src/agent_c_tools/src/agent_c_tools/tools/tool_debugger/README.md, src/agent_c_tools/src/agent_c_tools/tools/workspace_planning/html_converter.py, src/agent_c_tools/src/agent_c_tools/tools/workspace_planning/tests/__init__.py, src/agent_c_tools/src/agent_c_tools/tools/workspace_planning/tests/pytest.ini, src/agent_c_tools/src/agent_c_tools/tools/workspace_planning/tests/test_workspace_planning_integration.py, src/agent_c_tools/src/agent_c_tools/tools/workspace_planning/tool.py, src/agent_c_tools/src/agent_c_tools/tools/workspace_planning/z_manual_tool.py
This pull request introduces several updates to the `agent_c_tools` project, focusing on improving tool usage documentation, enhancing functionality for workspace planning tools, and adding support for HTML report generation. The most significant changes include the addition of examples for calling tool methods with or without prefixes, new functionality for exporting workspace planning reports in HTML format, and the creation of a standalone script for generating HTML reports from YAML files.
* Added detailed examples in `src/agent_c_tools/src/agent_c_tools/tools/tool_debugger/README.md` for calling tool methods with and without prefixes, explaining the usage of `use_prefix` in the `setup_tool` method.
* Introduced the `_format_response` method in …
=> Working with files

docs/tools/README_CSS_EXPLORER.md, docs/tools/README_MARIADB.md, src/agent_c_core/src/agent_c/agents/base.py, src/agent_c_tools/src/agent_c_tools/tools/agent_assist/base.py, src/agent_c_tools/src/agent_c_tools/tools/agent_clone/tool.py
This pull request introduces two major updates: documentation for new tools (`CSS Explorer Tool` and `MariaDB Database Tools`) and enhancements to agent context handling in the codebase. The documentation outlines the capabilities, use cases, and best practices for the tools, while the code changes improve the flexibility and functionality of agent-related methods by refining context management and callback handling.
* Added comprehensive documentation for the `CSS Explorer Tool`, detailing its capabilities, use cases, integration benefits, and best practices for working with component-based CSS files.
* Added detailed documentation for the `MariaDB Database Tools`, explaining its features for database connection, query execution, data analysis, and secure operations. Practical use cases …
=> Enhance tool context handling and session management in agent functions

agent_c_config/agents/recon_answers_oneshot.yaml, agent_c_config/agents/recon_oneshot.yaml, agent_c_config/agents/recon_revise_oneshot.yaml, personas/rita-requirements_engineer.md, src/agent_c_core/src/agent_c/agents/base.py, src/agent_c_tools/src/agent_c_tools/tools/agent_assist/base.py, src/agent_c_tools/src/agent_c_tools/tools/agent_clone/prompt.py, src/agent_c_tools/src/agent_c_tools/tools/agent_clone/tool.py, src/agent_c_tools/src/agent_c_tools/tools/reverse_engineering/tool.py, src/agent_c_tools/src/agent_c_tools/tools/workspace/base.py, src/agent_c_tools/src/agent_c_tools/tools/workspace/local_storage.py
This pull request introduces several updates to improve functionality and enhance clarity across multiple components of the `agent_c` project. The most significant changes include updates to agent personas and behaviors, enhancements to reverse engineering tools, and new functionality for workspace traversal. Below is a categorized summary of the most important changes:
* Added a new `CloneBehaviorSection` to define operating guidelines for agent clones, replacing the previous inline preamble with a structured section. This ensures consistency and modularity. (`[[1]](diffhunk://#diff-83503cd47fea5d9db6dfd706af0fec4a2a88c95f305b059c88713d046fe68f79R6-R20)`, `[[2]](diffhunk://#diff-e1d28846f92318a2e8fc1c6f58af104f977b7433826589f6ccb8fede07298fceL21-R23)`, …
=> Updates to tooling and agent personas based on lessons learned from last night run.

personas/rita-requirements_engineer.md
This pull request updates the `personas/rita-requirements_engineer.md` file to enhance the requirements engineering process by introducing a new project initialization phase and refining the analysis phase. 
Enhancements to the requirements engineering process:
* Added a new "Phase 0: Initialize Project Infrastructure" section to establish a foundation for the project, including creating a master plan, initializing metadata for tracking, and organizing scratchpad notes.
* Refined the analysis phase by removing an unnecessary blank line for improved clarity and formatting.
=> Removed accidentally deleted block of Rita.

src/agent_c_tools/src/agent_c_tools/tools/reverse_engineering/tool.py
This pull request introduces updates to the `query_analysis` method in the `reverse_engineering/tool.py` file, improving functionality and readability. Key changes include the addition of YAML support, adjustments to parameter naming for clarity, and a restructured implementation of the method to enhance its output and error handling.
* **Added YAML support for output formatting**: Introduced the `yaml` library to format the final response from the agent in YAML, improving readability and supporting Unicode characters. [[1]](diffhunk://#diff-40c8b9f3a62f928bc55964a24bbd3bf1d88541b8978689a1ff0683e31a1ca645R4-R5) [[2]](diffhunk://#diff-40c8b9f3a62f928bc55964a24bbd3bf1d88541b8978689a1ff0683e31a1ca645L131-R144)
* **Improved response handling**: Modified the `query_analysis` method to handle …
=> Update query_analysis to the new way of handling oneshots

agent_c_config/agents/recon_answers_oneshot.yaml, agent_c_config/agents/recon_oneshot.yaml, agent_c_config/agents/recon_revise_oneshot.yaml, src/agent_c_core/src/agent_c/config/agent_config_loader.py, src/agent_c_core/src/agent_c/models/agent_config.py, src/agent_c_core/src/agent_c/models/context/base.py, src/agent_c_core/src/agent_c/models/context/interaction_context.py, src/agent_c_core/src/agent_c/util/uncish_path.py, src/agent_c_tools/src/agent_c_tools/tools/workspace_planning/tool.py
This pull request introduces several updates to enhance agent configuration management, improve context modeling, and refactor workspace planning tools. Key changes include adding a `key` field to agent configurations, introducing new context models, and replacing custom path parsing logic with a new `UNCishPath` utility class.
* Added a `key` field to `AgentConfigurationV2` for unique identification and ensured it defaults to the `name` if not provided (`src/agent_c_core/src/agent_c/models/agent_config.py`). [[1]](diffhunk://#diff-1fb90723469bf0f301899b259f94b2f0119008bc8f44783e8f143d7c0ae84d6dR25) [[2]](diffhunk://#diff-1fb90723469bf0f301899b259f94b2f0119008bc8f44783e8f143d7c0ae84d6dR36-R42)
* Updated agent configuration YAML files to include the `key` field and renamed agents for …
=> New model for context, new helper for UNCPaths

src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/repositories/chat_repository.py, src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/repositories/user_repository.py, src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/services/chat_service.py, src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/services/session_service.py, src/agent_c_core/src/agent_c/toolsets/tool_chest.py, src/agent_c_core/src/agent_c/util/uncish_path.py
This pull request introduces structured logging to the `chat_repository`, `user_repository`, and `session_service` modules to improve observability and error tracking. The changes primarily focus on integrating `structlog` for logging key events, durations, and errors in asynchronous operations.
* Added `structlog` for logging initialization, message storage, retrieval, and metadata operations. Logs include session IDs, message types, and durations for performance tracking. [[1]](diffhunk://#diff-62445db4afee2931752511042d38a6fac548b013be6d958f77978c9796b9ad76R3-R6) [[2]](diffhunk://#diff-62445db4afee2931752511042d38a6fac548b013be6d958f77978c9796b9ad76R27-R33) [[3]](diffhunk://#diff-62445db4afee2931752511042d38a6fac548b013be6d958f77978c9796b9ad76R42-R55) …
=> Misc fixes

src/agent_c_tools/src/agent_c_tools/tools/agent_assist/tool.py, src/agent_c_tools/src/agent_c_tools/tools/agent_clone/tool.py
This pull request introduces enhancements to the `agent_assist` and `agent_clone` tools by integrating Markdown rendering for better formatting of agent interactions, and by adding media rendering for improved visualization of requests and responses. The changes also include updates to dependencies and minor refactoring to support these features.
* **`agent_assist` tool**:
- Added Markdown rendering for agent requests and responses in the `oneshot` and `chat` methods. These are now wrapped in HTML using the `markdown` library for better formatting. (`src/agent_c_tools/src/agent_c_tools/tools/agent_assist/tool.py`, [[1]](diffhunk://#diff-c5f5e3ac65209117102de816ff0be591fc1270380eb65d6f49484422f78176c4R47-R63) [[2]](diffhunk://#diff-c5f5e3ac65209117102de816ff0be591fc1270380eb65d6f49484422f78 …
=> Improve the way the agent assit tools rport

src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_bridge.py, src/agent_c_core/src/agent_c/agents/base.py, src/agent_c_core/src/agent_c/agents/claude.py, src/agent_c_core/src/agent_c/models/events/chat.py, src/agent_c_tools/src/agent_c_tools/tools/agent_assist/base.py, src/agent_c_tools/src/agent_c_tools/tools/agent_assist/tool.py, src/agent_c_tools/src/agent_c_tools/tools/agent_clone/tool.py
This pull request introduces significant enhancements to the handling of streaming callbacks, event types, and error handling in the `agent_c` codebase. The most notable changes include the addition of new event types (`HistoryDeltaEvent` and `CompleteThoughtEvent`), improved callback handling for streaming events, and updates to ensure more robust and flexible handling of agent interactions.
* **Unified Streaming Callback Logic**: Refactored the streaming callback mechanism to allow dynamic injection of callbacks at runtime, removing the need to restore the original callback after execution. (`src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_bridge.py`, [[1]](diffhunk://#diff-28bc5184f60b617647c44cd86d7e90885fee567cc04bad4bdf9ffda2f4e533d7L919-L922) …
=> implment full event streaming for the agent assist tools.

agent_c_config/agents/dominic-bokf_domain_ba.yaml, src/agent_c_core/src/agent_c/agents/claude.py, src/agent_c_tools/src/agent_c_tools/tools/agent_assist/base.py, src/agent_c_tools/src/agent_c_tools/tools/agent_assist/tool.py, src/agent_c_tools/src/agent_c_tools/tools/agent_clone/tool.py, src/agent_c_tools/src/agent_c_tools/tools/agent_team/prompt.py
This pull request includes updates to improve error handling, enhance code clarity, and remove unused tools from configurations. The changes primarily focus on refining agent behavior, improving user feedback, and ensuring robust handling of edge cases.
* [`src/agent_c_tools/src/agent_c_tools/tools/agent_assist/tool.py`](diffhunk://#diff-c5f5e3ac65209117102de816ff0be591fc1270380eb65d6f49484422f78176c4L76-R76): Updated error messages in `oneshot` and `chat` methods to indicate transient errors and suggest retrying for better user guidance. [[1]](diffhunk://#diff-c5f5e3ac65209117102de816ff0be591fc1270380eb65d6f49484422f78176c4L76-R76) [[2]](diffhunk://#diff-c5f5e3ac65209117102de816ff0be591fc1270380eb65d6f49484422f78176c4L146-R146)
* …
=> Some small bug fixed

src/agent_c_api_ui/agent_c_api/src/agent_c_api/api/v1/files.py, src/agent_c_core/src/agent_c/agents/base.py, src/agent_c_core/src/agent_c/agents/claude.py, src/agent_c_core/src/agent_c/toolsets/tool_set.py, src/agent_c_tools/src/agent_c_tools/tools/web/tool.py, src/agent_c_tools/src/agent_c_tools/tools/workspace/tool.py
This pull request introduces several updates across multiple files, focusing on improving code clarity, refactoring for better maintainability, and enhancing functionality. Key changes include renaming variables for consistency, removing unused imports, adding YAML support, and refactoring methods to streamline workflows. Below is a categorized summary of the most significant changes:
* Replaced references to `agent` with `agent_bridge` in `upload_file` to align with updated naming conventions. (`src/agent_c_api/src/agent_c_api/api/v1/files.py`)
* Renamed `prompt_context["agent"]` to `prompt_context["agent_runtime"]` for better semantic clarity in `_render_contexts`. (`src/agent_c_core/src/agent_c/agents/base.py`)
* Removed unused imports such as `RemoteProtocolError` and reorganized …
=> Add token protections to the workspace and web tools

agent_c_config/agents/aria_csharp_architect.yaml, agent_c_config/agents/douglas_bokf_orchestrator.yaml, agent_c_config/agents/mason_csharp_craftsman.yaml, agent_c_config/agents/rex_requirements_miner.yaml, agent_c_config/agents/vera_test_strategist.yaml, docs/multi_agent_coordination_design_bible.md, src/agent_c_core/src/agent_c/models/context/interaction_context.py, src/agent_c_tools/src/agent_c_tools/tools/agent_assist/tool.py, src/agent_c_tools/src/agent_c_tools/tools/agent_clone/tool.py, src/agent_c_tools/src/agent_c_tools/tools/workspace_planning/models.py, src/agent_c_tools/src/agent_c_tools/tools/workspace_planning/prompt.py, src/agent_c_tools/src/agent_c_tools/tools/workspace_planning/tool.py
This pull request introduces two new agent configurations, `Aria - C# Solution Architect` and `Douglas - BOKF Design Team Orchestrator`, to enhance the capabilities of the BOKF design team. These agents are designed to specialize in modern C# architecture and team orchestration, respectively, and include detailed guidelines, methodologies, and tools to ensure systematic excellence and competitive advantage.
* Specializes in designing clean, modern, and testable C# architectures based on comprehensive requirements analysis.
* Implements core architectural patterns such as Clean Architecture, SOLID principles, and Domain-Driven Design, while leveraging modern C# technologies like .NET 8+, Dependency Injection, and Entity Framework Core.
* Provides a structured methodology for …
=> New agents, new bible

agent_c_config/agents/bobb_agent_builder.yaml, agent_c_config/agents/mason_csharp_craftsman.yaml
This pull request updates the configuration and documentation for the `bobb_agent_builder` in the `Agent C` framework. It introduces a new tool, corrects a typo, and significantly expands the guidelines for designing multi-agent teams, including best practices and references to supporting documentation.
* Added `AgentCloneTools` to the list of tools available for the `bobb_agent_builder` agent. This likely supports the new multi-agent team functionality.
* Fixed a typo in the persona guidelines, changing "thos rules" to "those rules" for clarity.
* Expanded the persona guidelines to include a detailed section on multi-agent team design. This includes:
- Fundamental design principles such as role separation, sequential processing, planning-tool-driven delegation, context window discipline, …
=> Upgrade Bob to handle multi-agent teams.

.agent_c.meta.yaml, agent_c_config/agents/aria_csharp_architect_gatekeeper.yaml, agent_c_config/agents/douglas_bokf_orchestrator_gatekeeper.yaml, agent_c_config/agents/mason_csharp_craftsman_gatekeeper.yaml, agent_c_config/agents/vera_test_strategist_gatekeeper.yaml
This pull request introduces a new agent configuration for Douglas, the Gatekeeper Modernization Orchestrator, to streamline the modernization of BOKF's critical financial transaction processing system. The configuration defines Douglas's role, strategic mission, interaction guidelines, and coordination protocols, emphasizing systematic execution and adherence to Shawn Wallace's technical authority.
* **Agent Role and Mission**: Douglas is described as the orchestrator leading a specialized team to modernize BOKF's Gatekeeper system, focusing on requirements analysis, architecture design, implementation, and testing to deliver superior C# solutions.
* **Critical Interaction and Approval Protocols**:
- Guidelines for workspace path verification and mandatory signoff protocols by Shawn …
=> BOKF Gatekeeper agents

src/agent_c_core/src/agent_c/toolsets/tool_chest.py, src/agent_c_tools/pyproject.toml, src/agent_c_tools/src/agent_c_tools/tools/dataframe/tool.py
This pull request includes changes to streamline dependencies and improve the modularity of the codebase by removing unused imports and modifying dependency usage. The most important changes involve adjustments to the `ydata_profiling` library usage, the removal of the `pyarrow` dependency, and the cleanup of unused imports across files.
* Removed the `pyarrow` dependency from the `pyproject.toml` file and corresponding imports in `tool_chest.py`, as it is no longer required. (`[[1]](diffhunk://#diff-e2be9e2d1a83ee0209dfa14a698162dc18640a4b9d8e81370790e570e20f28bbL8)`, `[[2]](diffhunk://#diff-884f927a285f241b97e63a19251a65a5bd6334aabef2b89ccca43380aff4e3e3L7-L8)`)
* Commented out the `ydata_profiling` dependency in `pyproject.toml` to potentially phase it out, while retaining its usage …
=> Fix some issues with the dataframe tool imports

src/agent_c_tools/src/agent_c_tools/tools/workspace/dynamic_command.py, src/agent_c_tools/src/agent_c_tools/tools/workspace/dynamic_command_prompt.py, src/agent_c_tools/src/agent_c_tools/tools/workspace/executors/local_storage/.agentc_policies.yaml, src/agent_c_tools/src/agent_c_tools/tools/workspace/executors/local_storage/secure_command_executor.py, src/agent_c_tools/src/agent_c_tools/tools/workspace/executors/local_storage/validators/lerna_validator.py, src/realtime_client/packages/demo/HTTPS_SETUP.md, src/realtime_client/packages/demo/package.json
This pull request introduces several improvements and policy updates to the dynamic command execution and validation system, with a focus on enhanced security, more flexible script allowlists, and improved error handling. The main changes include updates to command policies (especially for npm, pnpm, and lerna), improved error/failed status handling in the command executor, and enhancements to the lerna validator for better flag and script validation. Additionally, the documentation for HTTPS setup in the demo app has been corrected for certificate file naming.
**Policy and Allowlist Updates:**
* Expanded the allowed scripts for `npm`, `pnpm`, and `lerna` `run` commands to include `test:run`, and relaxed argument restrictions to allow passing extra arguments for `npm` and `lerna` scripts. …
=> Improve the responses to the agent about commands

src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/realtime_bridge.py, src/agent_c_core/src/agent_c/models/chat_history/chat_session.py, src/realtime_client/packages/core/src/events/EventStreamProcessor.ts, src/realtime_client/packages/ui/src/components/chat/MessageFooter.tsx, src/realtime_client/packages/ui/src/components/chat/MessageList.tsx, src/realtime_client/packages/ui/src/components/chat/__mocks__/sentinelTestUtils.ts, src/realtime_client/packages/ui/src/components/chat/__tests__/MessageList.autoscroll.test.tsx, src/realtime_client/packages/ui/src/components/chat/__tests__/MessageList.bulkloading.test.tsx, src/realtime_client/packages/ui/src/components/chat/__tests__/MessageList.racefix.test.tsx, src/realtime_client/packages/ui/src/components/chat/__tests__/MessageList.regression.test.tsx, src/realtime_client/packages/ui/src/components/chat/__tests__/MessageList.scrollfix.test.tsx, src/realtime_client/packages/ui/src/components/chat/__tests__/MessageList.sentinel.test.tsx, src/realtime_client/packages/ui/src/components/editor/MarkdownEditor.tsx, src/realtime_client/packages/ui/src/components/editor/MarkdownEditorClient.tsx, src/realtime_client/packages/ui/src/components/input/InputArea.tsx
This pull request introduces improvements to chat session management, message list auto-scrolling, and UI enhancements for token display. The major changes include the addition of a sentinel element for more reliable auto-scrolling in the chat message list, new utilities and tests for scroll behavior, and updates to the chat session and footer UI for clarity and robustness.
**Message List Auto-Scroll Improvements:**
* Refactored the `MessageList` component to use a hidden sentinel element (`scrollSentinelRef`) as the scroll target for reliable auto-scrolling, especially during session restoration and new message arrivals. This includes logic to handle initial mount and user scroll interruptions. (`[[1]](diffhunk://#diff-16b2667ae47c727265f79a2d86542fbce1a9933e5635e625d98a2ad0a04a26f3R58-R6 …
=> Fix a bunch of UI issues in the RT client.

src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_bridge.py, src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/realtime_bridge.py, src/agent_c_core/src/agent_c/chat/session_manager.py, src/realtime_client/packages/ui/src/components/chat/MessageList.tsx, src/realtime_client/packages/ui/src/components/chat/content-renderers/ImageContentRenderer.tsx, src/realtime_client/packages/ui/src/components/session/SessionNameDropdown.tsx, src/realtime_client/packages/ui/src/components/session/__tests__/SessionNameDropdown.test.tsx
This pull request introduces improved session management and user experience features for chat sessions, including support for renaming and deleting sessions, more robust session cache handling, and enhanced auto-scroll logic in the chat UI. These changes help ensure session state is correctly maintained and reflected across both backend and frontend, while providing a smoother user experience when interacting with chat messages and switching between sessions.
**Session Management Enhancements**
* Added support for renaming chat sessions in both backend (`AgentBridge` and `ChatSessionManager`) and frontend, allowing users to update session names and have changes reflected in the UI. [[1]](diffhunk://#diff-28bc5184f60b617647c44cd86d7e90885fee567cc04bad4bdf9ffda2f4e533d7R194-R209) …
=> Session managment works in RT demo client now

agent_c_config/agents/bobb_agent_builder.yaml, agent_c_config/clean_json_keys.py, agent_c_config/clean_json_keys.readme.md, src/agent_c_core/src/agent_c/models/agent_config.py
This pull request significantly updates and expands the agent persona and configuration instructions for the `bobb_agent_builder` in `agent_c_config/agents/bobb_agent_builder.yaml`. The changes modernize the documentation to align with the latest Agent C framework standards, clarify best practices for agent and team design, and introduce detailed guidelines for multi-agent coordination, workspace usage, and special agent types. The persona instructions are now more structured, comprehensive, and aligned with current architecture patterns.
Key improvements and additions include:
**Agent Configuration and Documentation Modernization**
- Replaces outdated instructions with a new mandate to always consult the latest documentation files before agent creation, specifying which files to check …
=> Bobb instruction change - New utility

src/agent_c_core/src/agent_c/agents/claude.py
This pull request introduces significant performance and memory optimizations to the `ClaudeChatAgent` class, focusing on how tool arguments and text deltas are processed during streaming. The main improvements are lazy JSON parsing for tool calls (except for the "think" tool, which preserves its immediate streaming behavior), batching of text deltas for better throughput, and caching of concatenated tool calls to reduce redundant computations. These changes maintain backward compatibility while improving efficiency.
**Performance and memory optimizations:**
* Tool arguments for non-think tools are now stored as raw JSON strings during streaming and only parsed to JSON at execution time, reducing memory usage. The "think" tool preserves its immediate parsing and streaming behavior for …
=> Cluade streaming optimizations

.agent_c.meta.yaml, learn/team_processes/development_team/00_process_overview.md, learn/team_processes/development_team/01_reference_material_through_line.md, learn/team_processes/development_team/02_new_feature_design_process.md, learn/team_processes/development_team/03_coordinator_to_specialist_workflow.md, learn/team_processes/development_team/04_dev_to_test_handoff_protocol.md, learn/team_processes/development_team/05_cross_package_coordination.md, learn/team_processes/development_team/06_quality_control_procedures.md, learn/team_processes/development_team/README.md, learn/team_processes/development_team/role_specific/README.md, learn/team_processes/development_team/role_specific/dev_specialist_procedures.md, learn/team_processes/development_team/role_specific/domo_meta_coordinator_procedures.md, learn/team_processes/development_team/role_specific/package_coordinator_procedures.md, learn/team_processes/development_team/role_specific/test_specialist_procedures.md, src/agent_c_core/src/agent_c/toolsets/__init__.py
This pull request introduces a comprehensive set of process documentation for the realtime agent team, focusing on coordination, reference material handling, and design-first development protocols. The changes establish a structured approach for managing work across four package domains, ensuring that user requirements are preserved, design rigor is enforced, and cross-package coordination is explicit and traceable.
**Process Architecture and Overview**
* Added a detailed process overview (`00_process_overview.md`) describing the team structure (4 Package Coordinators, 32 Specialists), package breakdowns, and the end-to-end flow from user request to delivery, including principles like unfiltered user context, design-first development, and quality control gates.
**Reference Material …
=> Create xeample dev team processes. 

agent_c_config/agents/recon_answers_oneshot.yaml, agent_c_config/agents/recon_oneshot.yaml, agent_c_config/agents/recon_revise_oneshot.yaml, agent_c_config/agents/rita_requirements_engineer.yaml
This pull request updates agent configuration files to introduce a coordinated clone-based analysis and delegation workflow for requirements reverse engineering. The changes add new tools, expand agent roles, and provide detailed templates and instructions for clone delegation, improving scalability and analysis quality across all stages (basic, enhanced, and query answering).
* Added `AgentCloneTools` to the `tools` section for all relevant agents, enabling the use of clones for parallelized analysis and research tasks. [[1]](diffhunk://#diff-48bf684410e432e312e388bf201eb5ac47cf616602d5c0e8653fb08d24c7d70bL11-R12) [[2]](diffhunk://#diff-9f9e63d197cf6c5dbd8d32388da1b9d1b85238669c0a25ac84204e34b673fc3cR16) [[3]](diffhunk://#diff-4d66a834c3bbbcf3e02556a3e8686ab52f7cb3c9661910ba582d1e7ac17bfe …
=> Add the BOKF version of Rita and her team

src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_bridge.py, src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/realtime_bridge.py, src/agent_c_core/src/agent_c/models/events/chat.py, src/agent_c_core/src/agent_c/prompting/basic_sections/env_info.py, src/agent_c_tools/src/agent_c_tools/tools/agent_assist/base.py, src/agent_c_tools/src/agent_c_tools/tools/agent_assist/tool.py, src/agent_c_tools/src/agent_c_tools/tools/agent_clone/tool.py, src/agent_c_tools/src/agent_c_tools/tools/bridge/tool.py
This pull request introduces several improvements to agent session handling, prompt construction, and agent tool responses, with a focus on better environment info presentation and more consistent, structured responses from agent tools. The changes also ensure that necessary tools are activated for resumed or newly set agents, and that session and environment metadata are handled more robustly.
**Prompt and environment information improvements:**
* Refactored the `EnvironmentInfoSection` in `env_info.py` to simplify and clarify the session information presented to the agent, removing unused environment rules and improving the formatting of session metadata. The section now expects a `chat_session` object and provides a concise summary of session ID, name, and user name. …
=> Add a tool to allow agents to name sessions

src/agent_c_tools/src/agent_c_tools/tools/excel/README.md, src/agent_c_tools/src/agent_c_tools/tools/excel/__init__.py, src/agent_c_tools/src/agent_c_tools/tools/excel/business_logic/__init__.py, src/agent_c_tools/src/agent_c_tools/tools/excel/business_logic/concurrency_manager.py, src/agent_c_tools/src/agent_c_tools/tools/excel/business_logic/excel_operations.py, src/agent_c_tools/src/agent_c_tools/tools/excel/business_logic/workbook_manager.py, src/agent_c_tools/src/agent_c_tools/tools/excel/models.py, src/agent_c_tools/src/agent_c_tools/tools/excel/test_import_fix.py, src/agent_c_tools/src/agent_c_tools/tools/excel/tests/COMPREHENSIVE_TEST_RESULTS_REPORT.md, src/agent_c_tools/src/agent_c_tools/tools/excel/tests/README.md, src/agent_c_tools/src/agent_c_tools/tools/excel/tests/__init__.py, src/agent_c_tools/src/agent_c_tools/tools/excel/tests/execute_tests.py, src/agent_c_tools/src/agent_c_tools/tools/excel/tests/pytest.ini, src/agent_c_tools/src/agent_c_tools/tools/excel/tests/run_tests.py, src/agent_c_tools/src/agent_c_tools/tools/excel/tests/test-requirements.txt, src/agent_c_tools/src/agent_c_tools/tools/excel/tests/test_business_component.py, src/agent_c_tools/src/agent_c_tools/tools/excel/tests/test_tool_integration.py, src/agent_c_tools/src/agent_c_tools/tools/excel/tool.py, src/agent_c_tools/src/agent_c_tools/tools/excel/validate_imports.py
A comprehensive Excel manipulation toolset designed for high-volume operations and multi-agent workflows.
The Excel Tools provide powerful Excel file manipulation capabilities specifically designed for:
- **High-volume data writing** (thousands to millions of records)
- **Multi-agent concurrent operations** with conflict resolution
- **Memory-efficient processing** for large datasets
- **Generic data processing** from any source
- **Bulk operations and batch processing**
=> New excel tool thoroughly tested and passed.

agent_c_config/_agent_viewer.html, agent_c_config/_plan_viewer.html, agent_c_config/model_configs.json, src/agent_c_api_ui/agent_c_api/src/agent_c_api/core/agent_bridge.py, src/agent_c_api_ui/agent_c_react_client/src/components/chat_interface/MessagesList.jsx, src/agent_c_api_ui/agent_c_react_client/src/components/chat_interface/VirtualizedMessagesList.jsx
This pull request introduces improvements to the old UI to enable it to work right now.  Make old UI honor user scrolling
Added two new Claude models (`claude-sonnet-4-20250514` and `claude-opus-4-1-20250805`) to `model_configs.json`, each with extended context window, tool support, multi-modal capabilities, and configurable parameters for advanced usage.
Also added static viewers for agents and plans, they reside under agent_config.
=> Release 1.0 pre quick old uifix
